### ISSUE TITLE
Daemon refusing to start when image registry is not responding

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1009]
When a docker image registry need to be checked but appears offline the daemon refuses to start.
I would say in this case the daemon should continue to start regardless. Of course affected servers should display a warning.

We've got a Garrys Mod server awaiting a container rebuild which causes the daemon trying to rebuild it.
Of course it checks if the image needs to be pulled:
```
"msg":"Checking if we need to update image quay.io/pterodactyl/core:source, if so it will happen now."
``` 
The daemon then continues being unresponsive until it reveals what the issue is:
```
"err":{"message":"(HTTP code 500) server error - Get https://quay.io/v2/: net/http: TLS handshake timeout"}"
``` 
Continuing with:
```
"You should forcibly quit this process (CTRL+C) and attempt to fix the issue."
```

**Comment by DaneEveritt** [comment]
```04:00:56.027Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
04:00:56.027Z ERROR wings: Encountered an error while attempting to fetch a fresh image. Continuing with existing system image. (image=quay.io/pterodactyl/core:java)
    Error: Error while pulling image: Get http://quay.io/v1/repositories/pterodactyl/core/images: dial tcp 127.0.0.1:80: getsockopt: connection refused
        at IncomingMessage.stream.on.data (/srv/daemon/src/helpers/image.js:105:33)
        at emitOne (events.js:116:13)
        at IncomingMessage.emit (events.js:211:7)
        at IncomingMessage.Readable.read (_stream_readable.js:475:10)
        at flow (_stream_readable.js:846:34)
        at resume_ (_stream_readable.js:828:3)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
04:00:56.028Z DEBUG wings: Creating new container... (server=8f5baec8-2692-4c26-b3f5-ee89bedf90b0)
04:00:56.061Z DEBUG wings: New docker container successfully created for server. (server=8f5baec8-2692-4c26-b3f5-ee89bedf90b0)```

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/daemon/commit/bc4b12b434771211ed4ad54f7f379098d4a70300

**Comment by MarkL4YG** [comment]
Thank you 👍
