### ISSUE TITLE
Server not stopping during scheduled restart

### ISSUE THREAD

**Issue by SubtypeZero** [pterodactyl/panel#1092]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.7.6 (panel) and 0.5.5 (daemon)
* Server's OS: Ubuntu 16.0.4.3 LTS
* Your Computer's OS & Browser: N/A

------------------------

I'm experiencing an issue with one of my servers during scheduled restarts. The server gets stuck on "Stopping" and when I checked the daemon logs I noticed some errors that appear at the same time. My other servers are working fine and I didn't modify any file permissions after installing the server, so I don't see any reason why there would be an issue with this particular server. This issue only seems to occur with my FiveM server, which uses the latest version of parkervcp's [FiveM egg](https://github.com/parkervcp/eggs/blob/master/GTA/FiveM/egg-five-m.json).

Kernel Version: `Linux n1 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Diagnostics Report: https://hastebin.com/nihiwaveca 

The error thrown while stopping:
```
04:00:23.555Z FATAL wings: (path=/v1/server/power, method=PUT)
    Error: Can't remove headers after they are sent
        at ServerResponse.OutgoingMessage.removeHeader (_http_outgoing.js:391:11)
        at ServerResponse.restifyWriteHead [as writeHead] (/srv/daemon/node_modules/restify/lib/response.js:426:14)
        at _cb (/srv/daemon/node_modules/restify/lib/response.js:326:14)
        at ServerResponse.send (/srv/daemon/node_modules/restify/lib/response.js:342:9)
        at Responses.generic204 (/srv/daemon/src/helpers/responses.js:35:25)
        at Object.Auth.server.restart.err [as callback] (/srv/daemon/src/controllers/routes.js:242:31)
        at /srv/daemon/node_modules/dockerode/lib/container.js:597:12
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:91:20)
```

**Comment by parkervcp** [comment]
Can you check php and nodejs versions please?

**Comment by DaneEveritt** [comment]
That error you posted doesn't really break anything, my guess is that the server has an invalid stop command causing it to not stop properly, thus the daemon thinks it is still stopping.

The fact that its getting to 'Stopping' indicates that the request is going through successfully.
