### ISSUE TITLE
Issue when trying to open a folder via SFTP

### ISSUE THREAD

**Issue by Bl4ckSpr4y** [pterodactyl/panel#1096]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.5.5
* Server's OS: CentOS 7
* Your Computer's OS & Browser: Windows 10, Filezilla 3.30.0
------------------------
`docker info` : https://hastebin.com/raw/jaxazakocu
`uname -a` : `Linux mc-fr-01 4.15.9-1.el7.elrepo.x86_64 #1 SMP Sun Mar 11 16:19:17 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`
The error: 
```12:39:50.824Z FATAL wings: A fatal error occured during an operation.
    Error: Cannot parse time: NaN
        at toUnixTimestamp (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2540:9)
        at attrsToBytes (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2521:17)
        at SFTPStream.name (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2289:19)
        at handleReadDir (/srv/daemon/src/http/sftp.js:184:49)
```

Connecting to SFTP works, but when I try to open a 24GB folder named plugins, that error appears. The large files aren't in the index of that the folder plugins, but in a subdirectory of that folder.
Edit: I deleted the 18GB subfolder and now SFTP works.

**Comment by nick-2017** [comment]
This is happening to me too
https://paste.nick04.com/raw/sewus.js
`05:23:16.125Z FATAL wings: A fatal error occured during an operation.
    Error: Cannot parse time: NaN
        at toUnixTimestamp (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2540:9)
        at attrsToBytes (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2521:17)
        at SFTPStream.name (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2289:19)
        at handleReadDir (/srv/daemon/src/http/sftp.js:208:42)
        at /srv/daemon/node_modules/async/dist/async.js:473:16
        at next (/srv/daemon/node_modules/async/dist/async.js:5329:29)
        at /srv/daemon/node_modules/async/dist/async.js:969:16
        at Async.waterfall (/srv/daemon/src/http/sftp.js:657:24)
        at nextTask (/srv/daemon/node_modules/async/dist/async.js:5324:14)
        at next (/srv/daemon/node_modules/async/dist/async.js:5331:9)`

**Comment by schrej** [comment]
How do I deserve this 😭 

@nick-2017 are you on the latest version of the daemon? What client are you using?

**Comment by nick-2017** [comment]
@schrej I'm on the latest version of Panel and Daemon

I'm using WinSCP

My docker info if needed: https://paste.nick04.com/akihi.makefile

**Comment by Bl4ckSpr4y** [comment]
@nick-2017 Could you send `npm run diagnostics`?

**Comment by DaneEveritt** [comment]
@schrej I assumed it was related to the recent SFTP changes, if it isn't I can dig into it more as well.

**Comment by schrej** [comment]
@DaneEveritt No it's fine, I don't think it's related to the SFTP changes though as it occured before the changes already, assuming he's actually on the latest version.

**Comment by nick-2017** [comment]
@Bl4ckSpr4y 

npm run diagnostics: https://paste.nick04.com/opuba.sql

**Comment by fabri2000779** [comment]
Hmmm i though that this was a issue only in our enviroment but we have the same issue aswell sometimes @DaneEveritt

**Comment by schrej** [comment]
@nick-2017 If you provide logs using your personal paste service make sure it stays up. Maybe just use https://hastebin.com ?

**Comment by sanderr2002** [comment]
This problem occurs for me when trying to list any directory in SFTP (Even / )
I am running daemon version 0.6.5
I tried connecting with Filezilla (version 3.26.0) and the Linux built in SFTP command. My putty just freazes when running ls.
https://bin.ptdl.co/ldsli/

**Comment by sanderr2002** [comment]
I used the sftp command in Linux just to test if this also fails.

It's just showing once because I tried rebooting the entire dedicated server. After that just tried sftp once. I can provide you a log file with the same error over and over again if you want.

**Comment by DaneEveritt** [comment]
I'm guessing this is happening in folders with a ton of files and the daemon just kind of explodes trying to process them all.

**Comment by sanderr2002** [comment]
@DaneEveritt this problem occurs even with clean minecraft vanilla installation. The built in file manager still works.

**Comment by DaneEveritt** [comment]
Okay, will try to take a look today. Can you provide the output from `npm run diagnostics` for me when this happens?

**Comment by sanderr2002** [comment]
https://gist.github.com/sanderr2002/3b03e454c57d5bb1b384320ca9a6535f

**Comment by sanderr2002** [comment]
Any update?

**Comment by mayed505** [comment]
This happens with the timestamp issue here:

https://i.imgur.com/4OB5bZD.png

**Comment by mayed505** [comment]
This can be fixed by deleting those files that have that bad timestamps. :)
