### ISSUE TITLE
Daemon 

### ISSUE THREAD

**Issue by SwiftyPlaysMC** [pterodactyl/panel#1112]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.7.6
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Win 10 & Chrome

I have gotten all the way to starting a server and i get the error:
` Error: (HTTP code 404) no such container - No such image: alpine:3.4
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

**Comment by parkervcp** [comment]
What are you trying to start here?

**Comment by SwiftyPlaysMC** [comment]
Im trying to start a minecraft server
