### ISSUE TITLE
Can't start a minecraft bungeecord server

### ISSUE THREAD

**Issue by lucasdidur** [pterodactyl/panel#1199]
I got this error on daemon (obs.: i started with sudo)

22:38:08.170Z ERROR wings: { errorId: 'ddHLrLYDugMltvCGLUMe' } (server=d4621313-34df-488b-8b3c-b5e8d4f1ad1d)
    Error: (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write -1 to cpu.cfs_quota_us: open /sys/fs/cgroup/cpu,cpuacct/docker/4805d393917fb74de0e304733c1a66c14e46510afac17897e1ddb2990750a1d2/cpu.cfs_quota_us: permission denied\\\"\"": unknown
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at IncomingMessage.emit (events.js:187:15)
        at IncomingMessage.EventEmitter.emit (domain.js:442:20)
        at endReadableNT (_stream_readable.js:1081:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by DaneEveritt** [comment]
This isn't a bug with our software, the documentation is pretty clear about the kernel requirements here.

https://pterodactyl-daemon.readme.io/docs/updating-ovh-kernel

**Comment by lucasdidur** [comment]
Thank you, I did not know about that this docker permission its related to system kernel. I updated and worked.
