### ISSUE TITLE
SFTP can't enter directory that contains a .url file

### ISSUE THREAD

**Issue by jacobgc** [pterodactyl/panel#1200]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.5.6
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Chrome (Filezilla used to connect via SFTP)

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

On one of my client's servers, when attempting to enter a folder that contains a .url file I/they get this: "Status:	Listing directory /garrysmod/addons" and it then hangs there until you re-logon to the SFTP server.

Daemon: 
```
Linux node-D-002 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Docker: 
```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.28GiB
Name: node-D-002
ID: CVZL:XA4F:T4DS:MYFA:YOL5:UZJO:4FOY:AQ24:Y63N:JRLW:67CM:44OS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FileZilla
2. Log on to the server
3. Attempt to open a folder with a .url file
4. Enjoy not being able to open it

**Expected behavior**
To be able to open the folder.

**Comment by Bl4ckSpr4y** [comment]
@jacobgc Do the daemon and FileZIlla show any errors?

**Comment by jacobgc** [comment]
Didn't think there was one cause FileZilla didn't show any, however on inspection, there is this: 

```
18:25:45.566Z ERROR wings: An exception was encountered while handling the SFTP subsystem. (server=e378c2b1-dbeb-4cd9-9bc7-bc0c3d3708ba)
    exception: {
      "code": "ETIMEDOUT",
      "errno": "ETIMEDOUT",
      "syscall": "read"
    }
    --
    stack: Error: read ETIMEDOUT
        at _errnoException (util.js:992:11)
        at TCP.onread (net.js:618:25)
    --
    identifier: CRmUzdzqrkLrNBDCokzPcOujVVzEFIggjZgCE0fCBAnZxT1GbEJqRZxkFBMgy9bT
```

**Comment by DaneEveritt** [comment]
Cannot reproduce.
