### ISSUE TITLE
[Daemon] Previous logs don't show in console on a refresh

### ISSUE THREAD

**Issue by TheFlash787** [pterodactyl/panel#1270]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.6.1 (HOTFIX)
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Firefox Quantum - Windows 10

**Describe the bug**
Since I updated to the hotfix that you pushed, I have been unable to view any previous logs in the console. This either happens when I go to the server, or when I refresh the console page. Not everybody has been having this issue but many have been and it is extremely inconvenient and makes using the panel very difficult. 

If you read the Discord chats, you will see that there are many who have been having this issue and that it has only been since you released the new update.

Daemon: **4.4.0-72-generic** and https://hastebin.com/ipuvozonor.java

**To Reproduce**
1. Go to the server's console
2: You not see any of the previous logs
OR
1: You are on the console with logs appearing
2: You refresh your page, those logs are gone.

**Expected behavior**
I expect the logs to appear after refreshing the page or when going to the server, a snippet of the logs will show. None of these happens.

Thanks!

**Comment by TheFlash787** [comment]
https://hastebin.com/hakidokane

Daemon logs ^

**Comment by DaneEveritt** [comment]
Accidentally swallowed some exceptions...

```
SyntaxError: Unexpected token d in JSON at position 1
    at JSON.parse (<anonymous>)
    at _.split.forEach.line (/srv/daemon/src/controllers/docker.js:305:48)
    at Array.forEach (<anonymous>)
    at ReadStream.on.data (/srv/daemon/src/controllers/docker.js:304:63)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2058:12)
SyntaxError: Unexpected token : in JSON at position 0
    at JSON.parse (<anonymous>)
    at _.split.forEach.line (/srv/daemon/src/controllers/docker.js:305:48)
    at Array.forEach (<anonymous>)
    at ReadStream.on.data (/srv/daemon/src/controllers/docker.js:304:63)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2058:12)
```

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/daemon/commit/140a6bda65487769563dd2f99a1f01e8a1b29e64

Thanks for letting me poke around on your machine.
