### ISSUE TITLE
not creating

### ISSUE THREAD

**Issue by V1rusFalcon** [pterodactyl/panel#1284]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.4
* Server's OS: Debian 9
* Your Computer's OS & Browser: Firefox

**Describe the bug**
  Error: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: p                                                                                                                                                             ermission denied
        at IncomingMessage.stream.on.data (/srv/daemon/src/helpers/image.js:105:                                                                                                                                                             33)
        at emitOne (events.js:116:13)
        at IncomingMessage.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:246:13)
        at IncomingMessage.Readable.push (_stream_readable.js:208:10)
        at HTTPParser.parserOnBody (_http_common.js:130:22)
        at Socket.socketOnData (_http_client.js:440:20)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)

Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8-1+0~20180725124257.2+stretch~1.gbp571e56, Copyright (c) 1999-2018, by Zend Technologies

Linux V1F 4.15.18-1-pve #1 SMP PVE 4.15.18-17 (Mon, 30 Jul 2018 12:53:35 +0200) x86_64 GNU/Linux

**To Reproduce**
1. create a minecraft server
2. see logs

**Expected behavior**
create and start the minecraft server

**Comment by DaneEveritt** [comment]
This is not a bug with our software. OpenVZ is not a supported system.

**Comment by DaneEveritt** [comment]
This is not a bug with our software.
