### ISSUE TITLE
unexpected - invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by codingJWilliams** [pterodactyl/panel#1306]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.6.5
* Server's OS: Ubuntu Server 18.04
* Your Computer's OS & Browser: Solus Linux, Firefox

**Describe the bug**

I'm having the exact same error detailed in #916, whenever I make a server. My panel/daemon was working correctly before I rebooted the Daemon's server, where I now get that exact error

* Debug info: https://gist.github.com/codingJWilliams/c2daa10623af788eaa98c420eecb8c10

**To Reproduce**
I'm not sure how you would reproduce this

**Expected behavior**
The server would create successfully and boot up

**Comment by parkervcp** [comment]
@codingJWilliams Can you give us the full error the daemon output. What you gave us doesn't actually have that.

**Comment by codingJWilliams** [comment]
Sorry!
```
jay@nightborn-mc /srv/daemon $ sudo npm start

> pteronode@0.6.5 start /srv/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

12:25:15.934Z  INFO wings: + ------------------------------------ +
12:25:15.940Z  INFO wings: | Running Pterodactyl Daemon v0.6.5    |
12:25:15.941Z  INFO wings: |        https://pterodactyl.io        |
12:25:15.941Z  INFO wings: |  Copyright 2015 - 2018 Dane Everitt  |
12:25:15.941Z  INFO wings: + ------------------------------------ +
12:25:15.941Z  INFO wings: Loading modules, this could take a few seconds.
12:25:16.407Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
12:25:16.499Z  INFO wings: Configuring user pterodactyl (id: 999) as the owner of all server files.
12:25:16.504Z  INFO wings: Configuring timezone file location...
12:25:16.505Z  INFO wings: Checking container networking environment...
12:25:16.516Z  INFO wings: Found network interface for daemon: pterodactyl_nw
12:25:16.517Z  INFO wings: Ensuring correct network interface for containers...
12:25:16.529Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
12:25:16.535Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
12:25:16.560Z  INFO wings: Checking existing eggs against Panel response...
12:25:16.564Z  INFO wings: Beginning server initialization process.
12:25:16.577Z  WARN wings: Container was not found. Attempting to recreate it. (server=ff227c4f-a811-4f35-be1a-268b28c1fe74)
12:25:16.582Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.
12:25:17.864Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
12:25:18.761Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist 
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    --
    additional: {
      "statusCode": 400,
      "json": {
        "message": "invalid mount config for type \"bind\": bind source path does not exist"
      }
    }
12:25:18.763Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
```
@parkervcp

**Comment by parkervcp** [comment]
@codingJWilliams does the folder `ff227c4f-a811-4f35-be1a-268b28c1fe74` exist in `/srv/daemon-data/`

**Comment by codingJWilliams** [comment]
```
jay@nightborn-mc /srv/daemon $ ls /srv/daemon-data/
39ca9e91-fe0e-4e86-a276-17d122b9407e  f03dc44c-5483-4eb7-97af-a4426673d191  ff227c4f-a811-4f35-be1a-268b28c1fe74
jay@nightborn-mc /srv/daemon $ 
```
@parkervcp yeah

**Comment by codingJWilliams** [comment]
Anything else you need @parkervcp ?

**Comment by DaneEveritt** [comment]
Is your daemon directory set to `/srv/daemon-data`? Is this server one that exists on the panel as well?

**Comment by DaneEveritt** [comment]
Closing, no response.

**Comment by Sir3lit** [comment]
The solution is to purge docker from the system and reinstall it.
