### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by MrArtem1337** [pterodactyl/panel#1319]
> pteronode@0.6.5 start /srv/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

19:21:53.569Z  INFO wings: + ------------------------------------ +
19:21:53.572Z  INFO wings: | Running Pterodactyl Daemon v0.6.5    |
19:21:53.572Z  INFO wings: |        https://pterodactyl.io        |
19:21:53.572Z  INFO wings: |  Copyright 2015 - 2018 Dane Everitt  |
19:21:53.572Z  INFO wings: + ------------------------------------ +
19:21:53.573Z  INFO wings: Loading modules, this could take a few seconds.
19:21:54.012Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
19:21:54.168Z  INFO wings: Configuring user pterodactyl (id: 998) as the owner of all server files.
19:21:54.173Z  INFO wings: Configuring timezone file location...
19:21:54.173Z  INFO wings: Checking container networking environment...
19:21:54.178Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: (HTTP code 404) unexpected - 404 page not found

        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    --
    additional: {
      "statusCode": 404,
      "json": "404 page not found\n"
    }
19:21:54.178Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.

**Comment by DaneEveritt** [comment]
This is not a bug with the software, but because you've provided none of the requested information from the issue template I cannot begin to try pointing you in the correct direction.

**Comment by MrArtem1337** [comment]
Я не понімаю
