### ISSUE TITLE
Don't delete install logs when installations fail.

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1358]
**Is your feature request related to a problem? Please describe.**
Attempting to install an Arama 3 server, but it seems to fail with code 5, I know what the issue is, BUT others may not... as wings deletes the `/srv/daemon/config/servers/<uuid>` folder and along with that the install log, so people are unable to see WHY it failed other then what the daemon says and claims install script failed

**Describe the solution you'd like**
Wings to NOT delete the install.log, and communicate to the panel that the installed failed and maybe provide the install.log in a separate window, kind of like the console that can be opened.

**Describe alternatives you've considered**
None other then trying to catch the install log before its deleted 😄

**Additional context**
Arma 3 was only used as an example as it happened to me, this could go for any install or any egg

Side note: Wings "Claims" to "Notify remote panel of server install status, but it fails to say anywhere that the install failed.  https://justmyrandomstuff.com/img/KZGbrWc.png as it claims its still "Installing" when in reality its doing nothing

**Comment by parkervcp** [comment]
If you have the daemon open in debug mode the install get's logged to the daemon. You can see where it is failing there.

**Comment by parkervcp** [comment]
I have run into the issue when installing and testing servers. It's hard to diagnose a failed install because the logs are removed in the process.

@DaneEveritt Can we look into not removing the folders on a failed install please?

```
ptero_1  | 16:15:18.985Z DEBUG wings: Pulling image areyouscared/ptero:openttd ... this could take a few minutes.
ptero_1  | 16:15:19.520Z DEBUG wings: Creating new container... (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.676Z DEBUG wings: New docker container successfully created for server. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.676Z DEBUG wings: Updating configuration file for server to point to new docker container. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.679Z DEBUG wings: Reinitializing egg core for server. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.684Z DEBUG wings: Loaded configuration and initalized server. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.684Z  WARN wings: Server booting is now BLOCKED. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.684Z  INFO wings: Blocking server boot until option installation process is completed. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.685Z DEBUG wings: Contacting remote server to pull scripts to be used. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.685Z DEBUG wings: Contacting panel to determine scripts to run for option processes. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.706Z DEBUG wings: Writing temporary file to be handed into the Docker container. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.707Z DEBUG wings: Pulling ubuntu:18.04 image if it is not already on the system. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:19.708Z  INFO wings: (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  |     Writing output of installation process to file. { file:
ptero_1  |        '/srv/daemon/config/servers/093d776e-2ffb-4d09-83db-d4cf3a46749d/install.log' }
ptero_1  | 16:15:19.809Z  INFO wings: Pulling image ubuntu:18.04 ... this could take a few minutes.
ptero_1  | 16:15:20.238Z  INFO wings: Temporarily suspending server to avoid mishaps... (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:20.238Z DEBUG wings: Running privileged docker container to perform the installation process. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:20.257Z DEBUG wings: Server has been marked as requiring a rebuild on next boot cycle. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:20.257Z  WARN wings: Server has been suspended. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | /mnt/install/install.sh: line 1: apk: command not found
ptero_1  | /mnt/install/install.sh: line 6: curl: command not found
ptero_1  | tar (child): openttd.tar.gz: Cannot open: No such file or directory
ptero_1  | tar (child): Error is not recoverable: exiting now
ptero_1  | tar: Child returned status 2
ptero_1  | tar: Error is not recoverable: exiting now
ptero_1  | chmod: cannot access 'openttd': No such file or directory
ptero_1  | /mnt/install/install.sh: line 12: curl: command not found
ptero_1  | /mnt/install/install.sh: line 14: unzip: command not found
ptero_1  | tar: opengfx*.tar: Cannot open: No such file or directory
ptero_1  | tar: Error is not recoverable: exiting now
ptero_1  | rm: cannot remove 'open*zip': No such file or directory
ptero_1  | rm: cannot remove 'open*tar': No such file or directory
ptero_1  | rm: cannot remove 'open*gz': No such file or directory
ptero_1  | /mnt/install/install.sh: line 20: curl: command not found
ptero_1  | 16:15:21.473Z FATAL wings: A fatal error was encountered while attempting to create a server.
ptero_1  |     Error: Install script failed with code 127
ptero_1  |         at DockerController.run (/srv/daemon/src/controllers/option.js:169:41)
ptero_1  |         at /srv/daemon/node_modules/dockerode/lib/docker.js:1417:11
ptero_1  |         at /srv/daemon/node_modules/dockerode/lib/container.js:783:7
ptero_1  |         at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)
ptero_1  |         at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
ptero_1  |         at IncomingMessage.emit (events.js:187:15)
ptero_1  |         at IncomingMessage.EventEmitter.emit (domain.js:460:23)
ptero_1  |         at endReadableNT (_stream_readable.js:1094:12)
ptero_1  |         at process._tickCallback (internal/process/next_tick.js:63:19)
ptero_1  | 16:15:21.475Z DEBUG wings: Clearing servers object... (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:21.475Z DEBUG wings: Attempting to remove container... (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:21.475Z DEBUG wings: Attempting to remove configuration files... (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:21.479Z  INFO wings: Server has been unsuspended. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:21.479Z DEBUG wings: Removed configuration folder. null (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:21.495Z  INFO wings: Notified remote panel of server install status.
ptero_1  | 16:15:21.615Z DEBUG wings: Removed docker container from system. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:15:21.615Z  INFO wings: Server deleted. (server=093d776e-2ffb-4d09-83db-d4cf3a46749d)
ptero_1  | 16:17:48.687Z DEBUG wings: Clearing servers object... (server=05da67a6-14d0-4296-9cd4-b677e144830f)
ptero_1  | 16:17:48.687Z DEBUG wings: Attempting to remove container... (server=05da67a6-14d0-4296-9cd4-b677e144830f)
ptero_1  | 16:17:48.687Z DEBUG wings: Attempting to remove configuration files... (server=05da67a6-14d0-4296-9cd4-b677e144830f)
ptero_1  | 16:17:48.690Z DEBUG wings: Removed configuration folder. null (server=05da67a6-14d0-4296-9cd4-b677e144830f)
ptero_1  | 16:17:48.845Z DEBUG wings: Removed docker container from system. (server=05da67a6-14d0-4296-9cd4-b677e144830f)
ptero_1  | 16:17:49.080Z  INFO wings: Server deleted. (server=05da67a6-14d0-4296-9cd4-b677e144830f)
```

**Comment by padarom** [comment]
> If you have the daemon open in debug mode the install get's logged to the daemon.
@parkervcp I couldn't find any notes regarding debug mode on the documentation. Could you give me a hint on how to enable debug mode?

**Comment by DaneEveritt** [comment]
https://github.com/pterodactyl/daemon/commit/f735cbf631d2d2d0b329dac956d4d04842c693bc
