### ISSUE TITLE
Error when trying to start daemon

### ISSUE THREAD

**Issue by Niickles** [pterodactyl/panel#1399]
Hello,

When I try to start the daemon I get this error and I have no clue what to do with it

```
[root@gravps daemon]# sudo npm start

> pteronode@0.6.8 start /home/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

21:41:42.585Z  INFO wings: + ------------------------------------ +
21:41:42.594Z  INFO wings: | Running Pterodactyl Daemon v0.6.8    |
21:41:42.594Z  INFO wings: |        https://pterodactyl.io        |
21:41:42.594Z  INFO wings: |  Copyright 2015 - 2018 Dane Everitt  |
21:41:42.594Z  INFO wings: + ------------------------------------ +
21:41:42.594Z  INFO wings: Loading modules, this could take a few seconds.
21:41:43.296Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
21:41:43.442Z  INFO wings: Configuring user pterodactyl (id: 993) as the owner of all server files.
21:41:43.448Z  INFO wings: Configuring timezone file location...
21:41:43.451Z  INFO wings: Checking container networking environment...
21:41:43.465Z  INFO wings: Found network interface for daemon: pterodactyl_nw
21:41:43.465Z  INFO wings: Ensuring correct network interface for containers...
21:41:43.479Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
21:41:43.482Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
21:41:43.581Z  INFO wings: Checking existing eggs against Panel response...
21:41:43.586Z  INFO wings: Beginning server initialization process.
21:41:43.589Z  INFO wings: Configuring websocket for daemon stats...
21:41:43.590Z  INFO wings: Configuring internal SFTP server...
21:41:43.604Z FATAL wings: A fatal error occured during an operation. (err.code=EADDRINUSE)
    Error: listen EADDRINUSE 0.0.0.0:2022
        at Server.setupListenHandle [as _listen2] (net.js:1360:14)
        at listenInCluster (net.js:1401:12)
        at doListen (net.js:1510:7)
        at _combinedTickCallback (internal/process/next_tick.js:142:11)
        at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

any ideas?

**Comment by Niickles** [comment]
I've got it to work, the port was already in use

**Comment by LeCodeCo** [comment]
This isn't an issue with the panel. Ask within the Discord. 😃

**Comment by karla431** [comment]
Hey! Care to share for the details? I'm having the same issue.

**Comment by Niickles** [comment]
> Hey! Care to share for some details? I'm having the same issue.

Cant remember what the fix was exactly, sorry

**Comment by parkervcp** [comment]
Discord exists for this kind of support.

**Comment by icedmoca** [comment]
This is not a bad error. Refresh your browser CTRL+F5 npm is already running.

**Comment by GertVerhoek** [comment]
> 
> 
> Hey! Care to share for some details? I'm having the same issue.

Did you figure it out eventually?
I have the same error but have already tried changing the ports, the address in  use keeps changing with them.
So the daemon blocks it's own access?

**Comment by karla431** [comment]
> > Hey! Care to share for some details? I'm having the same issue.
> 
> @karla431
> Did you figure it out eventually?
> I have the same error but have already tried changing the ports, the address in use keeps changing with them.
> So the daemon blocks it's own access?

No I didn't. However I'm guessing that it had something to do with the encryption. I'm suggesting to you that go to discord and ask for help from there
