### ISSUE TITLE
Can't enable Two-factor Authentication for Administrator account

### ISSUE THREAD

**Issue by feardevilz** [Pterodactyl/Panel#143]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [x] Bug or Issue
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other

## What Happens
Clicking Enable Two-factor Authentication gives an error "An error occured while attempting to perform this action. Please try again."

## How to Reproduce

1. Login
2. Click Account Security
3. Click Enable Two-Factor Authentication

## Error Logs

```

[2016-10-15 01:50:18] production.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /srv/pterodactyl/bootstrap/cache/compiled.php:8831
Stack trace:
#0 /srv/pterodactyl/bootstrap/cache/compiled.php(8155): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /srv/pterodactyl/bootstrap/cache/compiled.php(8083): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /srv/pterodactyl/bootstrap/cache/compiled.php(8079): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /srv/pterodactyl/bootstrap/cache/compiled.php(2446): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#5 /srv/pterodactyl/app/Http/Middleware/LanguageMiddleware.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /srv/pterodactyl/bootstrap/cache/compiled.php(9819): Pterodactyl\Http\Middleware\LanguageMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /srv/pterodactyl/bootstrap/cache/compiled.php(13401): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /srv/pterodactyl/bootstrap/cache/compiled.php(9819): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /srv/pterodactyl/bootstrap/cache/compiled.php(11853): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /srv/pterodactyl/bootstrap/cache/compiled.php(9819): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /srv/pterodactyl/bootstrap/cache/compiled.php(13147): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /srv/pterodactyl/bootstrap/cache/compiled.php(9819): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /srv/pterodactyl/bootstrap/cache/compiled.php(13084): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /srv/pterodactyl/bootstrap/cache/compiled.php(9819): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /srv/pterodactyl/bootstrap/cache/compiled.php(3171): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /srv/pterodactyl/bootstrap/cache/compiled.php(9819): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /srv/pterodactyl/vendor/dingo/api/src/Http/Middleware/Request.php(108): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /srv/pterodactyl/bootstrap/cache/compiled.php(9819): Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /srv/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /srv/pterodactyl/bootstrap/cache/compiled.php(9804): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /srv/pterodactyl/bootstrap/cache/compiled.php(2390): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /srv/pterodactyl/bootstrap/cache/compiled.php(2374): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#29 /srv/pterodactyl/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#30 {main}  
```

#### Output of `uname -a`:

```
Linux dev2 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

#### Output of `php -v` (if Panel):

```
PHP 7.0.11-2+deb.sury.org~trusty+2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11-2+deb.sury.org~trusty+2, Copyright (c) 1999-2016, by Zend Technologies
```

#### Output of `node -v` (if Daemon):

```
v6.8.0
```

**Comment by DaneEveritt** [comment]
Pretty sure I ran into this yesterday while testing some other things and pushed a fix unintentionally.

Regardless, 2FA is working correctly in `0.5.0-pre.3` so I'm going to leave this open for a bit, but it should be fixed already.

**Comment by feardevilz** [comment]
Thanks for taking a look. Just for notice, i did try v0.4.1 originally then also tried the 'develop' branch to see if it was fixed. I'm not sure if .5.0-pre3 is pushed into develop or not. 
thanks

**Comment by DaneEveritt** [comment]
It would be on the `feature/better-api` branch is is pretty unstable right now.
