### ISSUE TITLE
Strange 404 on file edit

### ISSUE THREAD

**Issue by rtm516** [pterodactyl/panel#1613]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.13
* Server's OS: Ubuntu 18.04.2 LTS
* Your Computer's OS & Browser: Chrome 75.0.3770.100 on Windows 10

**Describe the bug**
I get an error 404
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use). - PHP 7.2.19-0ubuntu0.18.04.1 

**To Reproduce**
1. Go to one of the servers
2. Choose file management
3. Pick a folder
4. Pick a sub-folder
5. Pick a file to edit
4. See error 404

**Expected behavior**
The file shows up when you click and you don't get an error 404.

**Further info**
The url that the page takes me to is `https://pterodactyl.url/server/server.id/files/edit/garrysmod%2Fcfg/server.cfg` but if i ajust this to `https://pterodactyl.url/server/server.id/files/edit/garrysmod/cfg/server.cfg` it works as expected.
After enabling `APP_REPORT_ALL_EXCEPTIONS=true` in the .env file I get 
```
[2019-06-20 22:44:41] production.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:179
Stack trace:
#0 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#5 /var/www/panel/public_html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/panel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /var/www/panel/public_html/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}  
```

**Comment by schrej** [comment]
There should be an actual error above the stack trace, could you provide that as well?

**Comment by rtm516** [comment]
> There should be an actual error above the stack trace, could you provide that as well?

Should be fixed it was there but forgot that github code tag ignores the text on the same line

**Comment by schrej** [comment]
This has been an issue in the past already: #621

**Comment by rtm516** [comment]
> This has been an issue in the past already: #621

I did try and look for one, must have missed that one.
