### ISSUE TITLE
please help  :D

### ISSUE THREAD

**Issue by jakub96124124** [pterodactyl/panel#1623]
FATAL wings: A fatal error was encountered while attempting to create a server.
    Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind mount source path does not exist: /srv/daemon-data/cb585d29-39f3-4cc4-aa5e-8d13f171df58
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:287:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:256:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:232:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
20:29:31.940Z  INFO wings: Server deleted. (server=cb585d29-39f3-4cc4-aa5e-8d13f171df58)
20:29:32.020Z  INFO wings: Notified remote panel of server install status.

**Comment by MatthewSH** [comment]
Uh, yeah. this is not support. Join the discord: https://discord.gg/pterodactyl

Please read the template issue next time.

**Comment by jakub96124124** [comment]
dík za radu debile !!!!

**Comment by DaneEveritt** [comment]
1.) Just because it isn't in english doesn't mean people don't understand you.
2.) Calling people assholes is generally an _excellent_ way to make it so no one will help you.

Cheers.
