### ISSUE TITLE
Docker & wings bug

### ISSUE THREAD

**Issue by srkhost** [pterodactyl/panel#1818]
Panel: 0.7.16
Wings: 0.6.12
Kernel Version: 4.19.0-6-amd64
Operating System: Debian GNU/Linux 10 (buster)
Server:
 Containers: 192
  Running: 134
  Paused: 0
  Stopped: 58
 Images: 93
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683

```
ERROR wings: (HTTP code 409) unexpected - You cannot remove a running container 7c7826fa2d190d86926570c5f7a065a06b885f8d5730df97e5e27334d718d512. Stop the container before attempting removal or force remove  (server=bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e)
    Error: (HTTP code 409) unexpected - You cannot remove a running container 7c7826fa2d190d86926570c5f7a065a06b885f8d5730df97e5e27334d718d512. Stop the container before attempting removal or force remove
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at IncomingMessage.emit (events.js:194:15)
        at IncomingMessage.EventEmitter.emit (domain.js:441:20)
        at endReadableNT (_stream_readable.js:1103:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

```
After I remove docker containter with
 **docker rm bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e -f**
and restart it in the panel I get this message:  

```
ERROR wings: (HTTP code 403) unexpected - endpoint with name bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e already exists in network pterodactyl_nw  (server=bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e)
    Error: (HTTP code 403) unexpected - endpoint with name bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e already exists in network pterodactyl_nw
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at IncomingMessage.emit (events.js:194:15)
        at IncomingMessage.EventEmitter.emit (domain.js:441:20)
        at endReadableNT (_stream_readable.js:1103:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```

To fix this I used this command: 
**docker network disconnect -f pterodactyl_nw bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e**
and I can't join to server.
After if I rebuild the container, the problem repeats itself.

So the best option is to delete the whole server and create it again..

```
ERROR wings: (HTTP code 500) server error - driver failed programming external connectivity on endpoint bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e (cae9cf3900dbaf4202f1e0739d020fbc3a82ef92f183ad4fb74bf7c5693bad8d): Bind for ***.***.***.***:8284 failed: port is already allocated  (server=bb8c74e9-9c83-4f95-a6d7-c1fef0e2870e)
    Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint 1cbf8129-fb1a-46c7-aebc-19c88bd43e5d (cae9cf3900dbaf4202f1e0739d020fbc3a82ef92f183ad4fb74bf7c5693bad8d): Bind for ***.***.***.***:8284 failed: port is already allocated
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at IncomingMessage.emit (events.js:194:15)
        at IncomingMessage.EventEmitter.emit (domain.js:441:20)
        at endReadableNT (_stream_readable.js:1103:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```

**To Reproduce**
I don't know.. really..

**Expected behavior**
I used swapoff command to disable swap.

**Comment by SaigyoujiYuyuko233** [comment]
I have the same problem exactly like this. I try to use ``docker network disconnect` ` command to remove the connection and it works. But there is another problem: I disconnect the network so people can not access this server.

**Comment by SaigyoujiYuyuko233** [comment]
I found a solution in Stackoverflow.
![image](https://user-images.githubusercontent.com/39913604/75316910-91f5b780-58a1-11ea-83f7-754cb3f3afc5.png)
It works for me!

**Comment by srkhost** [comment]
Woah, thanks.

I will try it :)

**Comment by DaneEveritt** [comment]
You're forcibly removing a container, which is going to leave dangling artifacts. This is an issue with how you're trying to use docker, and not with this software, at least for the artifacts.

The container still running while trying to remove is likely a de-sync in the daemon, which rebooting the daemon should fix. I'm not going to dig into this any more though, since the daemon would need serious attention to even warrant getting far enough in the weeds to fix this. The limited remaining resources I have are all focused on the new version of the software.
