### ISSUE TITLE
Daemon: docker-compose network

### ISSUE THREAD

**Issue by kamcio96** [pterodactyl/panel#1841]
Docker compose configuration creates additional network. Sometimes it override pterodactyl_nw ip address. I suggest to define pterodactyl_nw in docker-compose.yml

```
{"name":"wings","hostname":"daemon","pid":13,"level":50,"msg":"You should forcibly quit this process (CTRL+C) and attempt to fix the issue.","time":"2020-03-04T00:13:02.034Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"+ ------------------------------------ +","time":"2020-03-04T00:13:03.223Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"| Running Pterodactyl Daemon v0.0.0-canary    |","time":"2020-03-04T00:13:03.224Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"|        https://pterodactyl.io        |","time":"2020-03-04T00:13:03.224Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"|  Copyright 2015 - 2019 Dane Everitt  |","time":"2020-03-04T00:13:03.224Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"+ ------------------------------------ +","time":"2020-03-04T00:13:03.224Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"Loading modules, this could take a few seconds.","time":"2020-03-04T00:13:03.224Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"Modules loaded, starting Pterodactyl Daemon...","time":"2020-03-04T00:13:03.454Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"Configuring user pterodactyl (id: 100) as the owner of all server files.","time":"2020-03-04T00:13:03.467Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"Configuring timezone file location...","time":"2020-03-04T00:13:03.496Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":30,"msg":"Checking container networking environment...","time":"2020-03-04T00:13:03.496Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":40,"msg":"No isolated network interface for containers was detected, creating one now.","time":"2020-03-04T00:13:03.502Z","v":0}
{"name":"wings","hostname":"daemon","pid":31,"level":60,"err":{"message":"(HTTP code 403) unexpected - Pool overlaps with other one on this address space ","name":"Error","stack":"Error: (HTTP code 403) unexpected - Pool overlaps with other one on this address space \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17\n    at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)\n    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:448:20)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"additional":{"statusCode":403,"json":{"message":"Pool overlaps with other one on this address space"}},"msg":"A fatal error caused the daemon to abort the startup.","time":"2020-03-04T00:13:03.504Z","v":0}
```

**Comment by parkervcp** [comment]
You can specify a range in the config for the daemon. Docker networks get allocated on creation. It's better to specify the network in compose than let them allocate willy nilly
