### ISSUE TITLE
Subusers on server can't use SFTP even with proper permissions

### ISSUE THREAD

**Issue by KewaiiGamer** [pterodactyl/panel#1972]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-beta.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser:  Windows 10 & Chrome

**Describe the bug**
A clear and concise description of what the bug is. Subusers with SFTP permissions can't use SFTP unless they are server owner
Panel: `php -v` (the php version in use). PHP 7.4.3

**To Reproduce**
1. Add an subuser to a server
2. Give All permissions (including permissions in the File category)
3. Connect to SFTP with that user
4. "Authentication Failed"

**Expected behavior**
The subuser should be allowed to connect to SFTP as long as it has SFTP permission

**Comment by Sir3lit** [comment]
It seems like when @DaneEveritt moved from a permissions table to it being inside of `subusers` table this was left out. It's making the call of 
```
select * from `permissions` where `permissions`.`subuser_id` in (2)`
``` 
and it's causing the panel to 500 and in turn, failing the auth for the sftp server as nothing is returned. 

Logs are as follows

Wings:
```
error	sftp	sftp-server@v1.1.1/server.go:84	encountered error validating user crendentials	{"error": "QueryException: An error was encountered while processing this request. (HTTP/500)", "errorVerbose": "QueryException: An error was encountered while processing this request. (HTTP/500)\ngithub.com/pterodactyl/wings/api.(*PanelRequest).ValidateSftpCredentials\n\t/Users/dane/Sites/development/code/wings/api/sftp_endpoints.go:28\ngithub.com/pterodactyl/wings/sftp.validateCredentials\n\t/Users/dane/Sites/development/code/wings/sftp/server.go:78\ngithub.com/pterodactyl/sftp-server.(*Server).Initalize.func1\n\t/Users/dane/go/pkg/mod/github.com/pterodactyl/sftp-server@v1.1.1/server.go:77\ngolang.org/x/crypto/ssh.(*connection).serverAuthenticate\n\t/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:479\ngolang.org/x/crypto/ssh.(*connection).serverHandshake\n\t/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:277\ngolang.org/x/crypto/ssh.NewServerConn\n\t/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:206\ngithub.com/pterodactyl/sftp-server.Server.AcceptInboundConnection\n\t/Users/dane/go/pkg/mod/github.com/pterodactyl/sftp-server@v1.1.1/server.go:144\nruntime.goexit\n\t/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337\ngithub.com/pterodactyl/wings/api.(*PanelRequest).ValidateSftpCredentials\n\t/Users/dane/Sites/development/code/wings/api/sftp_endpoints.go:28\ngithub.com/pterodactyl/wings/sftp.validateCredentials\n\t/Users/dane/Sites/development/code/wings/sftp/server.go:78\ngithub.com/pterodactyl/sftp-server.(*Server).Initalize.func1\n\t/Users/dane/go/pkg/mod/github.com/pterodactyl/sftp-server@v1.1.1/server.go:77\ngolang.org/x/crypto/ssh.(*connection).serverAuthenticate\n\t/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:479\ngolang.org/x/crypto/ssh.(*connection).serverHandshake\n\t/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:277\ngolang.org/x/crypto/ssh.NewServerConn\n\t/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:206\ngithub.com/pterodactyl/sftp-server.Server.AcceptInboundConnection\n\t/Users/dane/go/pkg/mod/github.com/pterodactyl/sftp-server@v1.1.1/server.go:144\nruntime.goexit\n\t/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337"}
github.com/pterodactyl/sftp-server.(*Server).Initalize.func1
	/Users/dane/go/pkg/mod/github.com/pterodactyl/sftp-server@v1.1.1/server.go:84
golang.org/x/crypto/ssh.(*connection).serverAuthenticate
	/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:479
golang.org/x/crypto/ssh.(*connection).serverHandshake
	/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:277
golang.org/x/crypto/ssh.NewServerConn
	/Users/dane/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200403201458-baeed622b8d8/ssh/server.go:206
github.com/pterodactyl/sftp-server.Server.AcceptInboundConnection
	/Users/dane/go/pkg/mod/github.com/pterodactyl/sftp-server@v1.1.1/server.go:144

```
Panel:
```
[2020-04-25 10:18:15] production.ERROR: QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.permissions' doesn't exist (SQL: select * from `permissions` where `permissions`.`subuser_id` in (2)) in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\Database\Connection->run
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\Database\Connection->select
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\Database\Query\Builder->runSelect
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\Database\Query\Builder->onceWithColumns
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(537): Illuminate\Database\Query\Builder->get
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\Database\Eloquent\Builder->getModels
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(155): Illuminate\Database\Eloquent\Builder->get
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(144): Illuminate\Database\Eloquent\Relations\Relation->get
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(585): Illuminate\Database\Eloquent\Relations\Relation->getEager
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(554): Illuminate\Database\Eloquent\Builder->eagerLoadRelation
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(522): Illuminate\Database\Eloquent\Builder->eagerLoadRelations
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\Database\Eloquent\Builder->get
#14 /var/www/pterodactyl/app/Repositories/Eloquent/SubuserRepository.php(99): Illuminate\Database\Eloquent\Builder->first
#15 /var/www/pterodactyl/app/Services/Sftp/AuthenticateUsingPasswordService.php(90): Pterodactyl\Repositories\Eloquent\SubuserRepository->getWithPermissionsUsingUserAndServer
#16 /var/www/pterodactyl/app/Http/Controllers/Api/Remote/SftpAuthenticationController.php(67): Pterodactyl\Services\Sftp\AuthenticateUsingPasswordService->handle
#17 (0): Pterodactyl\Http\Controllers\Api\Remote\SftpAuthenticationController->__invoke
#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array
#19 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction
#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch
#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController
#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}
#24 /var/www/pterodactyl/app/Http/Middleware/Api/Daemon/DaemonAuthenticate.php(85): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Pterodactyl\Http\Middleware\Api\Daemon\DaemonAuthenticate->handle
#26 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle
#28 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#29 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then
#30 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack
#31 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute
#32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute
#33 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch
#34 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}
#35 /var/www/pterodactyl/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#36 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle
#37 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#38 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle
#39 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#40 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle
#41 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#42 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle
#43 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#44 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle
#45 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#46 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle
#47 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}
#48 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then
#49 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter
#50 /var/www/pterodactyl/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle
```
