### ISSUE TITLE
Daemon fails to report server start due to JSON.parse Syntax Error (Modded Minecraft)

### ISSUE THREAD

**Issue by NopeDK** [pterodactyl/panel#1976]
Starting the server using the panel sometimes result in the panel being stuck in "Starting" as the daemon encounters and error and doesn't report a successful start.

When this occurs, the console in the panel also does not update unless you restart/stop/kill the instance. If you write a command, nothing happens until you refresh the page and the console now shows everything that has happened since you last refreshed the page.

wings.log:
```
{"name":"wings","hostname":"xxxx","pid":##,"server":"xxxx","level":30,"msg":"Server status has been changed to STARTING","time":"2020-04-26T11:43:04.735Z","v":0}
{"name":"wings","hostname":"xxxx","pid":##,"level":60,"err":{"message":"Unexpected token l in JSON at position 151","name":"SyntaxError","stack":"SyntaxError: Unexpected token l in JSON at position 151\n    at JSON.parse (<anonymous>)\n    at Tail.<anonymous> (/srv/daemon/src/controllers/docker.js:248:40)\n    at Tail.emit (events.js:310:20)\n    at Tail.EventEmitter.emit (domain.js:482:12)\n    at ReadStream.<anonymous> (/srv/daemon/node_modules/tail/lib/tail.js:44:31)\n    at ReadStream.emit (events.js:310:20)\n    at ReadStream.EventEmitter.emit (domain.js:482:12)\n    at addChunk (_stream_readable.js:286:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at ReadStream.Readable.push (_stream_readable.js:209:10)"},"msg":"A fatal error occured during an operation.","time":"2020-04-26T11:45:28.052Z","v":0}
```

latest.log:
```
[13:45:28] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 1118 advancements
[13:45:28] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 30 advancement trees
[13:45:28] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (13.085s)! For help, type "help" or "?"
[13:45:28] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting GS4 status listener
[13:45:28] [Query Listener #1/INFO] [net.minecraft.server.MinecraftServer]: Query running on x.x.x.x
```

**Comment by parkervcp** [comment]
@Nobody196 You did not fill out any information in the issue template.

We ask for this information so we know what version of the panel and daemon you are seeing these issues with.

I am closing this issue. Please open a new issue with the information we request.

**Comment by parkervcp** [comment]
@NopeDK
