### ISSUE TITLE
Unknown operating system with Ubuntu 18.04

### ISSUE THREAD

**Issue by Lars225** [pterodactyl/panel#2022]
Hey Guys on Installing the Pterodactyl Deamon i become this error:

14:09:07.389Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})
    Error: Unable to create a pterodactyl user and group, unknown operating system.
        at Async.waterfall (/srv/daemon/src/index.js:200:34)
        at nextTask (/srv/daemon/node_modules/async/dist/async.js:5324:14)
        at next (/srv/daemon/node_modules/async/dist/async.js:5331:9)
        at /srv/daemon/node_modules/async/dist/async.js:969:16
        at Getos (/srv/daemon/src/index.js:176:21)
        at /srv/daemon/node_modules/getos/index.js:95:16
        at wrapper (/srv/daemon/node_modules/getos/node_modules/async/dist/async.js:268:20)
        at iteratorCallback (/srv/daemon/node_modules/getos/node_modules/async/dist/async.js:495:17)
        at /srv/daemon/node_modules/getos/node_modules/async/dist/async.js:321:20
        at /srv/daemon/node_modules/getos/index.js:90:18
14:09:07.389Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.

Dedicated Server with Ubuntu 18.04 LTS

**Comment by parkervcp** [comment]
Please fill out the items we requested in the form when you submitted this.
