### ISSUE TITLE
Unable to determine size of server data folder

### ISSUE THREAD

**Issue by uselesssupport** [pterodactyl/panel#2024]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.13
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
"level":40,"err":{"message":"Unable to determine size of server data folder, exited with code 1 signal null.","name":"Error","stack":"Error: Unable to determine size of server data folder, exited with code 1 signal null.\n    at ChildProcess.Exec.on (/srv/daemon/src/controllers/fs.js:89:29)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)"},"msg":"Unable to determine size of server data folder, exited with code 1 signal null.","time":"2020-05-12T18:29:51.

**Also I would like an explanation on where it shows that a server is being killed for output throttles.**

**To Reproduce**
1. Unable to reproduce.

**Expected behavior**
No errors.

**Comment by Sir3lit** [comment]
Iirc this happens when the servers config file exists but not the data directory. As it was deleted when the server was deleted but the cinfug wasn't. Look for extra config files in /srv/daemon/config/servers

**Comment by phoenixnodes** [comment]
This is causing a server to unexpectedly shutdown, there are no additional files in the folder you mentioned. @Sir3lit

**Comment by uselesssupport** [comment]
This is happening to a server that still exists. There are no additional config files in the folder mentioned.

**Comment by Sir3lit** [comment]
Can you do `ls -la`  in the /srv/daemon-data folder and post the output

**Comment by uselesssupport** [comment]
`
total 48
drwxr-xr-x 12 root        root        4096 May 10 19:57 .
drwxr-xr-x  4 root        root        4096 May  5 16:12 ..
drwxr-xr-x  8 pterodactyl pterodactyl 4096 May 11 16:15 xxxxxxxx-c89f-456e-a30d-367636a82fc9
drwxr-xr-x 11 pterodactyl pterodactyl 4096 May 12 11:38 xxxxxxxx-4a15-4913-96d8-eedd954ae785
drwxr-xr-x 12 pterodactyl pterodactyl 4096 May  9 00:30 xxxxxxxx-85ef-47a0-b279-9eec04daa760     <---- Issue server
drwxr-xr-x  4 pterodactyl pterodactyl 4096 May  9 16:32 xxxxxxxx-4456-4522-bfc1-f21155663e29
drwxr-xr-x 19 pterodactyl pterodactyl 4096 May  9 13:53 xxxxxxxx-a6ec-40a1-b5cc-411796975583
drwxr-xr-x 17 pterodactyl pterodactyl 4096 May  5 19:41 xxxxxxxx-4818-4583-b1b8-849c3a49338a
drwxr-xr-x 13 pterodactyl pterodactyl 4096 May  6 14:42 xxxxxxxx-80c9-4b3e-9a4e-a43512a68e37
drwxr-xr-x 18 pterodactyl pterodactyl 4096 May  6 18:32 xxxxxxxx-a125-4156-8620-083fcaca4362
drwxr-xr-x  3 pterodactyl pterodactyl 4096 May 10 19:56 xxxxxxxx-16ed-4a3d-999a-42cf9eef45ff
drwxr-xr-x  8 pterodactyl pterodactyl 4096 May  7 09:48 xxxxxxxx-6ad3-425e-a24c-1c724e0cea83
`

**Comment by Sir3lit** [comment]
It would show in the console if it was killed for the limit, a way to test is to remove the limit or set it to something it would never reach... I highly doubt that it failing to get the server folder size would cause it to stop the server unless it's hitting its limit.

**Comment by uselesssupport** [comment]
Would this be visible in the server logs? Or only in the console during the shutdowns which seem to occur at random times which would be very difficult to catch if this was the reason it was shutting down. I wish this was logged in some way so I could check whether its being shut down because of the limit or something else.
