### ISSUE TITLE
add support for private registries

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#210]
Need the support for private docker registries.

Already triied to manualy login on the registry being logged as root on the node, the pull still fail

```json
{"name":"wings","hostname":"ptero-node-1","pid":1872,"level":50,"err":{"message":"(HTTP code 500) server error - {\"message\":\"Get https://hub.company.com/v2/ptero/docker-csgo-sourcemod/tags/list: denied: access forbidden\"}\n ","name":"Error","stack":"Error: (HTTP code 500) server error - {\"message\":\"Get https://hub.company.com/v2/ptero/docker-csgo-sourcemod/tags/list: denied: access forbidden\"}\n \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:229:17\n   at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:256:9)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"},"msg":"(HTTP code 500) server error - {\"message\":\"Get https://hub.company.com/v2/ptero/docker-csgo-sourcemod/tags/list: denied: access forbidden\"}\n ","time":"2016-12-13T22:47:10.196Z","v":0}
```

Manual pull is working.

**Comment by DaneEveritt** [comment]
closed in Pterodactyl/Daemon@f7170d6
