### ISSUE TITLE
wings crashes with docker 1.12.4

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#211]
When using docker version 1.12.4 wings crashes on startup.

```
08:44:37.199Z INFO wings: Loading modules, this could take a few seconds.
08:44:38.042Z INFO wings: Modules loaded, starting Pterodactyl Daemon...
08:44:38.049Z INFO wings: Checking container networking environment...
08:44:38.055Z INFO wings: Attempting to start SFTP service container...
08:44:38.1032 wings: A fatal error caused the daemon to stop abruptly. (er r.code=ECONNRESET)
    Error: socket hang up at
        createHangUpError (_http client.js:254:15)
        at Socket.socketOnEnd (_http client.js:346:23)
        at emitNone (events.js:91:20)
        at Socket.emit (events.js:185:7)
        at endReadableNT (stream readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    --
    additional: {
        "code": "ECONNRESET" 
    }
```

This could be an issue with [dockerode](https://github.com/apocas/dockerode).

Or it is related with the warning for the 1.12.4 [release](https://github.com/docker/docker/releases/tag/v1.12.4). We should test with a fresh 1.12.4 installation of docker.

**Comment by DaneEveritt** [comment]
Associated trace:
```
Trace
    at Async.auto.err (/srv/daemon/src/index.js:124:10)
    at /srv/daemon/node_modules/async/dist/async.js:484:16
    at /srv/daemon/node_modules/async/dist/async.js:1764:17
    at apply (/srv/daemon/node_modules/async/dist/async.js:41:25)
    at /srv/daemon/node_modules/async/dist/async.js:76:12
    at /srv/daemon/node_modules/async/dist/async.js:988:16
    at Object.DockerController.listNetworks [as callback] (/srv/daemon/src/controllers/network.js:46:29)
    at /srv/daemon/node_modules/dockerode/lib/docker.js:507:10
    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:225:19)
    at ClientRequest.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:210:10)
```

**Comment by DaneEveritt** [comment]
Issue created at https://github.com/docker/docker/issues/29411

**Comment by DaneEveritt** [comment]
fixed in https://github.com/Pterodactyl/Daemon/commit/0df7cac7cedd8c9b9e100affdfcbef5258c83af1
