### ISSUE TITLE
Folder with corresponding server UUID not being created

### ISSUE THREAD

**Issue by xiurobert** [pterodactyl/panel#2233]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.13
* Server's OS: Ubuntu Server 20.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
On attempting to create a server, Docker reports that the bind mount configuration is invalid. Running the list directory command in /srv/daemon-data returns no results. This suggests that the folder has not been created.

This is the error produced.
```
 FATAL wings: A fatal error was encountered while attempting to create a server.
    Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /srv/daemon-data/15cc53ff-ab01-4b9e-adff-c82e7e38c23c
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:287:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:256:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:232:14)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:466:23)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```

Output of `npm run diagnostics` [here](https://ptero.co/izufoviruz).

`uname -a`: 
```
Linux <hostname> 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

`docker info:`
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version:
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu Core 16
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.7GiB
 Name: <hostname>
 ID: TPYP:UTZW:XIN4:ZSWR:ZVXQ:YKPO:UKML:B7V3:YPA3:JPYR:PG3C:UIFQ
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**To Reproduce**

1. Attempt to create a new server. Any egg works
2. Await installation to fail
3. View the error in the console window (if the daemon was started with `npm start`)
4. Open up a new TTY and run `ls /srv/daemon-data` to confirm that folder has not been created

**Expected behavior**
Directory should be created and server should have started

**Comment by xiurobert** [comment]
To add on, I notice that this was in #916 and it was supposedly fixed in 8ddb71a9bd30e09cf106879fd284932442f5c940

**Comment by xiurobert** [comment]
Another update. I've been trying to debug the issue on my own for a while. I've logged the output of the callback from ensureDir but to my surprise the directories have now been created. However, the issue still persists. Am now attempting to reinstall docker.

**Comment by xiurobert** [comment]
Seems that removing the apt installed docker and installing it from the convenience script seems to have done the trick as seen in #1293 and #1381
