### ISSUE TITLE
Loading egg that doesn't exist anymore

### ISSUE THREAD

**Issue by INfoUpgraders** [pterodactyl/panel#2264]
Daemon
* Version of Daemon: v0.6.13
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Google Chrome (latest)

**Describe the bug**
```
20:26:32.231Z  WARN wings: Container was not found. Attempting to recreate it. (server=f231cc5a-098f-41c0-b01c-bebd25ef2156)
20:26:32.330Z  INFO wings: Checking if we need to update image github.com/INfoUpgraders/pterodactyl-eggs/tree/master/rust, if so it will happen now.
20:26:32.335Z ERROR wings: Encountered an error while attempting to fetch a fresh image. Continuing with existing system image.
    Error: (HTTP code 400) unexpected - invalid reference format: repository name must be lowercase 
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:9)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:448:20)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    --
    image: github.com/INfoUpgraders/pterodactyl-eggs/tree/master/rust
20:26:32.340Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: (HTTP code 400) unexpected - invalid reference format: repository name must be lowercase 
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:287:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:256:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:232:14)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:448:20)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    --
    additional: {
      "statusCode": 400,
      "json": {
        "message": "invalid reference format: repository name must be lowercase"
      }
    }
```

**To Reproduce**
1. Make a bad egg and update it
2. Delete the egg and start wings

**Expected behavior**
For the daemon not to completely break like this.

**Comment by matthewpi** [comment]
The only reason a container is being pulled is because a server still has the bad Docker Image.  Servers have their own Docker Image field which isn't updated when the egg is updated.  The daemon isn't completely broken either, the server just fails to boot because the image cannot be pulled.
