### ISSUE TITLE
erro ao iniciar servidor

### ISSUE THREAD

**Issue by zuckszinho** [pterodactyl/panel#2267]
Olá quando inicio meu servidor do pterodatyl ele retorna isso no console: 
[Pterodactyl Daemon] A fatal error was encountered while starting this server.

Nas logs do Ubuntu 20.04 aparece isso:
01:10:37.236Z ERROR wings: (HTTP code 500) server error - driver failed programming external connectivity on endpoint 1c988b0f-242a-439d-98e9-a40f548ef2ad (f3378d29d9bb31be6a2206aa9356894caaf26e26e2f26bd4d73b100b502ac8bf): Error starting userland proxy: listen tcp 31.220.19.53:22004: bind: cannot assign requested address  (server=1c988b0f-242a-439d-98e9-a40f548ef2ad)
    Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint 1c988b0f-242a-439d-98e9-a40f548ef2ad (f3378d29d9bb31be6a2206aa9356894caaf26e26e2f26bd4d73b100b502ac8bf): Error starting userland proxy: listen tcp 31.220.19.53:22004: bind: cannot assign requested address
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:287:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:256:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:232:14)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:448:20)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

ME AJUDEM POR FAVOR!!!!

**Comment by DaneEveritt** [comment]
Please seek support in our Discord server, as our support bot will be able to give you the exact answer you need. In addition, you didn't even fill out the template. :(
