### ISSUE TITLE
Attempting to delete a failed backup results in 500 error

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2280]
**Background (please complete the following information):**
* Panel or Daemon: Wings, Possibly both?
* Version of Panel/Daemon: rc2 for panel, latest build for wings from Dane in discord
* Server's OS: Ubuntu 18.04

**Describe the bug**
Attempting to delete a failed backup results in a 500 error.
```
[2020-08-28 01:59:05] production.ERROR: GuzzleHttp\Exception\ServerException: Server error: `DELETE https://node4.justmyrandomstuff.com:8080/api/servers/d6657d41-d6f5-499d-8198-2d816fbd82d4/backup/ad57ab78-6d43-4fb4-a5ac-95295b02bb5e` resulted in a `500 Internal Server Error` response:
{"error":"An unexpected error was encountered while processing this request.","error_id":"bcbaa083-6b27-4577-9741-19b5f6 (truncated...)
```
**To Reproduce**
1. Create a failed backup with broken rc2 wings
2. move to new wings built by Dane.
3. try to delete the failed backup.

**Expected behavior**
The 500 to be ignored as I'm guessing its caused by it not actually existing on the machine, and remove it from the database.

**Comment by DaneEveritt** [comment]
Can you also get the Panel log since there are kind of two bugs here?

**Comment by Sir3lit** [comment]
You referring to the stack trace?

**Comment by DaneEveritt** [comment]
Oh wow sorry I was tired when I looked at that. That should have hit wings, since wings gave you back a request reference: `bcbaa083-6b27-4577-9741-19b5f6` (which got a bit truncated, but should be enough to grep the logs for).

**Comment by Sir3lit** [comment]
I had runs open and never seen the request in debug

**Comment by Sir3lit** [comment]
![ZimKRJg](https://user-images.githubusercontent.com/1757840/91629090-bbe47f80-e993-11ea-8ddc-6e129535b199.gif)

Here is the stack from the logs 

```json
{
   "errors":[
      {
         "code":"DaemonConnectionException",
         "status":"500",
         "detail":"There was an exception while attempting to communicate with the daemon resulting in a HTTP\/500 response code. This exception has been logged.",
         "source":{
            "line":78,
            "file":"\/app\/Repositories\/Wings\/DaemonBackupRepository.php"
         },
         "meta":{
            "trace":[
               "#0 \/var\/www\/pterodactyl\/app\/Services\/Backups\/DeleteBackupService.php(72): Pterodactyl\\Repositories\\Wings\\DaemonBackupRepository->delete()",
               "#1 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Concerns\/ManagesTransactions.php(28): Pterodactyl\\Services\\Backups\\DeleteBackupService->Pterodactyl\\Services\\Backups\\{closure}()",
               "#2 \/var\/www\/pterodactyl\/app\/Services\/Backups\/DeleteBackupService.php(83): Illuminate\\Database\\Connection->transaction()",
               "#3 \/var\/www\/pterodactyl\/app\/Http\/Controllers\/Api\/Client\/Servers\/BackupController.php(118): Pterodactyl\\Services\\Backups\\DeleteBackupService->handle()",
               "#4 [internal function]: Pterodactyl\\Http\\Controllers\\Api\\Client\\Servers\\BackupController->delete()",
               "#5 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(54): call_user_func_array()",
               "#6 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()",
               "#7 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()",
               "#8 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(196): Illuminate\\Routing\\Route->runController()",
               "#9 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(685): Illuminate\\Routing\\Route->run()",
               "#10 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()",
               "#11 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/Client\/Server\/AuthenticateServerAccess.php(81): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#12 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Client\\Server\\AuthenticateServerAccess->handle()",
               "#13 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/AuthenticateIPAccess.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#14 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\AuthenticateIPAccess->handle()",
               "#15 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/AuthenticateKey.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#16 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\AuthenticateKey->handle()",
               "#17 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/ApiSubstituteBindings.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#18 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/Client\/SubstituteClientApiBindings.php(60): Pterodactyl\\Http\\Middleware\\Api\\ApiSubstituteBindings->handle()",
               "#19 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Client\\SubstituteClientApiBindings->handle()",
               "#20 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/IsValidJson.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#21 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\IsValidJson->handle()",
               "#22 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#23 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()",
               "#24 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/SetSessionDriver.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#25 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\SetSessionDriver->handle()",
               "#26 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#27 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()",
               "#28 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#29 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()",
               "#30 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()",
               "#31 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#32 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()",
               "#33 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()",
               "#34 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(628): Illuminate\\Routing\\Router->runRoute()",
               "#35 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()",
               "#36 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()",
               "#37 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()",
               "#38 \/var\/www\/pterodactyl\/vendor\/fideloper\/proxy\/src\/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#39 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()",
               "#40 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#41 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
               "#42 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#43 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
               "#44 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#45 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()",
               "#46 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#47 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()",
               "#48 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#49 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()",
               "#50 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#51 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()",
               "#52 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()",
               "#53 \/var\/www\/pterodactyl\/public\/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()",
               "#54 {main}"
            ]
         }
      }
   ]
}
```

As you see wings is running, and i never see the `delete` request.

**Comment by JanDevDE** [comment]
@DaneEveritt The same, but a different issue for me. Backup deletion also fails with error 500, but in my case, the backup itself failed (see other issues from me) so "is_successful" is 0 in the database. So when I try to delete this failed backup I get an error 500. I guess DELETE doesn't work if the file doesn't exist, so I think to change the code so it doesn't care if it exists or not on a failed backup.

Error:

ERROR: [Aug 31 17:01:29.796] encountered HTTP/500 error while handling request error=stat /var/lib/pterodactyl/backups/ec635d8c-1882-465a-91b9-9a192421f5e9.tar.gz: no such file or directory error_id=25f5c33
        /go/wings/router/router_server_backup.go:55
DEBUG: [Aug 31 17:01:29.797] DELETE /api/servers/44d877cf-26a3-41e0-b3ca-8121281ba3a5/backup/ec635d8c-1882-465a-91b9-9a192421f5e9 client_ip=192.168.208.1 latency=897.167µs status=500
