### ISSUE TITLE
Unable to extract archives that are created by the panel.

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2332]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: Rc5 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
Trying to unarchive a file archived by the panel results in an HTTP 500 and the following logs in wings.

500 Response 
```json
{
   "errors":[
      {
         "code":"DaemonConnectionException",
         "status":"500",
         "detail":"There was an exception while attempting to communicate with the daemon resulting in a HTTP\/500 response code. This exception has been logged.",
         "source":{
            "line":269,
            "file":"\/app\/Repositories\/Wings\/DaemonFileRepository.php"
         },
         "meta":{
            "trace":[
               "#0 \/var\/www\/pterodactyl\/app\/Http\/Controllers\/Api\/Client\/Servers\/FileController.php(241): Pterodactyl\\Repositories\\Wings\\DaemonFileRepository->decompressFile()",
               "#1 [internal function]: Pterodactyl\\Http\\Controllers\\Api\\Client\\Servers\\FileController->decompress()",
               "#2 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(54): call_user_func_array()",
               "#3 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()",
               "#4 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()",
               "#5 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(196): Illuminate\\Routing\\Route->runController()",
               "#6 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(685): Illuminate\\Routing\\Route->run()",
               "#7 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()",
               "#8 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/Client\/Server\/AuthenticateServerAccess.php(84): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#9 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Client\\Server\\AuthenticateServerAccess->handle()",
               "#10 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/AuthenticateIPAccess.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#11 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\AuthenticateIPAccess->handle()",
               "#12 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/AuthenticateKey.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#13 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\AuthenticateKey->handle()",
               "#14 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/ApiSubstituteBindings.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#15 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/Client\/SubstituteClientApiBindings.php(60): Pterodactyl\\Http\\Middleware\\Api\\ApiSubstituteBindings->handle()",
               "#16 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Client\\SubstituteClientApiBindings->handle()",
               "#17 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/IsValidJson.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#18 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\IsValidJson->handle()",
               "#19 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#20 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()",
               "#21 \/var\/www\/pterodactyl\/app\/Http\/Middleware\/Api\/SetSessionDriver.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#22 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\SetSessionDriver->handle()",
               "#23 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#24 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()",
               "#25 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#26 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()",
               "#27 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()",
               "#28 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#29 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()",
               "#30 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()",
               "#31 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(628): Illuminate\\Routing\\Router->runRoute()",
               "#32 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()",
               "#33 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()",
               "#34 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()",
               "#35 \/var\/www\/pterodactyl\/vendor\/fideloper\/proxy\/src\/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#36 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()",
               "#37 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#38 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
               "#39 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#40 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
               "#41 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#42 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()",
               "#43 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#44 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()",
               "#45 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#46 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()",
               "#47 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
               "#48 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()",
               "#49 \/var\/www\/pterodactyl\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()",
               "#50 \/var\/www\/pterodactyl\/public\/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()",
               "#51 {main}"
            ]
         }
      }
   ]
}
```

```
DEBUG: [Sep 12 22:27:46.014] POST /api/servers/26ced393-99f4-4b30-a380-380e2ab1daac/files/decompress client_ip=88.198.68.87 latency=1.177589168s status=500
DEBUG: [Sep 12 22:28:16.275] GET /api/servers/26ced393-99f4-4b30-a380-380e2ab1daac/files/list-directory?directory=%2F1 clent_ip=88.198.68.87 latency=130.543µs status=200
DEBUG: [Sep 12 22:29:35.269] GET /api/servers/26ced393-99f4-4b30-a380-380e2ab1daac/files/list-directory?directory=%2F1 client_ip=88.198.68.87 latency=120.423µs status=200
ERROR: [Sep 12 22:29:40.850] encountered HTTP/500 error while handling request error=walking factorio: could not extract file from archive: open /var/lib/pterodactyl/volumes/26ced393-99f4-4b30-a380-380e2ab1daac/bin/x64/factorio: text file busy error_id=36fdd48c-6c9f-46f0-8961-f4ba5d677827 server=26ced393-99f4-4b30-a380-380e2ab1daac

Stacktrace:
github.com/pterodactyl/wings/router.TrackedServerError
        /home/runner/work/wings/wings/router/error.go:36
github.com/pterodactyl/wings/router.postServerDecompressFiles
        /home/runner/work/wings/wings/router/router_server_files.go:349
github.com/gin-gonic/gin.(*Context).Next
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/pterodactyl/wings/router.ServerExists
        /home/runner/work/wings/wings/router/middleware.go:80
github.com/gin-gonic/gin.(*Context).Next
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161

DEBUG: [Sep 12 22:29:40.852] POST /api/servers/26ced393-99f4-4b30-a380-380e2ab1daac/files/decompress client_ip=88.198.68.87 latency=1.173198366s status=500
```

**To Reproduce**
1. Use the File Manager to make an archive.
2. Try to extract that archive.

**Expected behavior**
For it to work...

**Comment by DaneEveritt** [comment]
This looks like you tried to extract an archive over a file that was actively being used by the server process? Does it work if the server is stopped?

**Comment by DaneEveritt** [comment]
Per Discord discussion, file was in use. Will handle this error specifically to return a more user friendly message.
