### ISSUE TITLE
Unable to Remove subusers

### ISSUE THREAD

**Issue by DamonOnYT** [pterodactyl/panel#2359]
**Background (please complete the following information):**
Panel v1.0.0-rc.6
Webserver Apache2

**Describe the bug**
When going to remove a sub user, I am greeted with a 404 error

**To Reproduce**
Head to the subusers tab
Press the trashbin on an existing subuser

![Image](http://ben.has-raped.me/7YztTpx.png)

**Expected behavior**
Deletes the subsuer

**Comment by DaneEveritt** [comment]
I cannot reproduce this with existing or fresh subusers.

**Comment by DamonOnYT** [comment]
> I cannot reproduce this with existing or fresh subusers.

I somehow managed to delete 1 user, but there is still another subuser that I am unable to delete with that 404 error.

**Comment by Sir3lit** [comment]
Was able to reproduce this by making a new sub-user then attempting to delete it. Below is the stack trace.

```
{
    "errors": [
        {
            "code": "NotFoundHttpException",
            "status": "404",
            "detail": "No query results for model [Pterodactyl\\Models\\Subuser].",
            "source": {
                "line": 222,
                "file": "/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
            },
            "meta": {
                "trace": [
                    "#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(198): Illuminate\\Foundation\\Exceptions\\Handler->prepareException()",
                    "#1 /var/www/pterodactyl/app/Exceptions/Handler.php(159): Illuminate\\Foundation\\Exceptions\\Handler->render()",
                    "#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): Pterodactyl\\Exceptions\\Handler->render()",
                    "#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\\Routing\\Pipeline->handleException()",
                    "#4 /var/www/pterodactyl/app/Http/Middleware/Api/Client/Server/AuthenticateServerAccess.php(84): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Client\\Server\\AuthenticateServerAccess->handle()",
                    "#6 /var/www/pterodactyl/app/Http/Middleware/Api/AuthenticateIPAccess.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\AuthenticateIPAccess->handle()",
                    "#8 /var/www/pterodactyl/app/Http/Middleware/Api/AuthenticateKey.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\AuthenticateKey->handle()",
                    "#10 /var/www/pterodactyl/app/Http/Middleware/Api/ApiSubstituteBindings.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#11 /var/www/pterodactyl/app/Http/Middleware/Api/Client/SubstituteClientApiBindings.php(60): Pterodactyl\\Http\\Middleware\\Api\\ApiSubstituteBindings->handle()",
                    "#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Client\\SubstituteClientApiBindings->handle()",
                    "#13 /var/www/pterodactyl/app/Http/Middleware/Api/IsValidJson.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\IsValidJson->handle()",
                    "#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()",
                    "#17 /var/www/pterodactyl/app/Http/Middleware/Api/SetSessionDriver.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\SetSessionDriver->handle()",
                    "#19 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()",
                    "#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()",
                    "#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()",
                    "#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()",
                    "#26 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()",
                    "#27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()",
                    "#28 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()",
                    "#29 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()",
                    "#30 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()",
                    "#31 /var/www/pterodactyl/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()",
                    "#33 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#34 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
                    "#35 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#36 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
                    "#37 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#38 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()",
                    "#39 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#40 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()",
                    "#41 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#42 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()",
                    "#43 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#44 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()",
                    "#45 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()",
                    "#46 /var/www/pterodactyl/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()",
                    "#47 {main}"
                ]
            }
        }
    ]
}
```

**Comment by zKoz210** [comment]
It's easy to reproduce:
1) Creating a single user
2) Open the list of users in a new tab
3) in the first tab, delete the user, then try to delete in the second tab and get an error

**Comment by zKoz210** [comment]
I don't understand why there is a confusion of UUID and names.

The UUID displayed above is somehow a user with mail test@gmail.com, although in fact it is the last in the list with a completely different UUID

![image](https://user-images.githubusercontent.com/28255085/94339501-21fc0b00-0003-11eb-8e71-68445cff4c6f.png)
![image](https://user-images.githubusercontent.com/28255085/94339605-c54d2000-0003-11eb-9cf5-0ba02ad6f379.png)
