### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by shootdot** [pterodactyl/panel#2363]
I am having an issue on build I tried to change the login page and just edited the image of login page I am running Panel v1 and when I saved and tried to build it the build failed. Please help asap Error: -
`ERROR in ./resources/scripts/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .only must be an array, or undefined
    at assertArray (/var/www/pterodactyl/node_modules/@babel/core/lib/config/validation/option-assertions.js:150:11)
    at assertIgnoreList (/var/www/pterodactyl/node_modules/@babel/core/lib/config/validation/option-assertions.js:157:15)
    at /var/www/pterodactyl/node_modules/@babel/core/lib/config/validation/options.js:107:5
    at Array.forEach (<anonymous>)
    at validateNested (/var/www/pterodactyl/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/var/www/pterodactyl/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at /var/www/pterodactyl/node_modules/@babel/core/lib/config/config-chain.js:174:34
    at cachedFunction (/var/www/pterodactyl/node_modules/@babel/core/lib/config/caching.js:32:19)
    at buildRootChain (/var/www/pterodactyl/node_modules/@babel/core/lib/config/config-chain.js:120:36)
    at loadPrivatePartialConfig (/var/www/pterodactyl/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/var/www/pterodactyl/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/var/www/pterodactyl/node_modules/babel-loader/lib/index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/www/pterodactyl/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/var/www/pterodactyl/node_modules/babel-loader/lib/index.js:5:194)
    at /var/www/pterodactyl/node_modules/babel-loader/lib/index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/var/www/pterodactyl/node_modules/babel-loader/lib/index.js:5:97)
    at Object._loader (/var/www/pterodactyl/node_modules/babel-loader/lib/index.js:224:18)
    at Object.loader (/var/www/pterodactyl/node_modules/babel-loader/lib/index.js:60:18)
    at Object.<anonymous> (/var/www/pterodactyl/node_modules/babel-loader/lib/index.js:55:12)
 @ multi react-hot-loader/patch ./resources/scripts/index.tsx main[1]
`

**Comment by Sir3lit** [comment]
It should be stated that he's using node v10.22.1 then updated to v12.18 and got the error above. while doing `yarn build` / `yarn build:production` is also using yarn v 1.22.5
Below is the image he posted in discord. 
![image](https://user-images.githubusercontent.com/1757840/93572304-aabfda80-f963-11ea-9f96-9808a7b7d23a.png)

**Comment by DaneEveritt** [comment]
Thats weird, since the Panel development repo uses Node 12 for builds: https://github.com/pterodactyl/development/blob/master/build/Dockerfile-panel#L6

**Comment by tmunsch** [comment]
I am having the same issue, I am running Centos7 and i have verified my versions are correct. Anything i can do to help? I can give you SSH access if you would like. It's just my dev enviroment.
