### ISSUE TITLE
Error code 500 in Daemon

### ISSUE THREAD

**Issue by hansputera** [pterodactyl/panel#2459]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon:  0.6.13
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows Chrome 

**Describe the bug**
Error code 500 while start the daemon `npm start`

**To Reproduce**
1. Go to '/srv/daemon'
2. Enter `./config/core.json` then type `npm start`
3. Waiting

**Expected behavior**
```js
root@panel:/srv/daemon# npm start

> pteronode@0.6.13 start /srv/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

04:11:08.358Z  INFO wings: + ------------------------------------ +
04:11:08.360Z  INFO wings: | Running Pterodactyl Daemon v0.6.13    |
04:11:08.360Z  INFO wings: |        https://pterodactyl.io        |
04:11:08.360Z  INFO wings: |                                      |
04:11:08.360Z  INFO wings: |  Copyright 2015 - 2020 Dane Everitt  |
04:11:08.360Z  INFO wings: |           and contributors           |
04:11:08.360Z  INFO wings: + ------------------------------------ +
04:11:08.360Z  INFO wings: Loading modules, this could take a few seconds.
04:11:08.646Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
04:11:08.667Z  INFO wings: Creating keypair to use for SFTP connections.
04:11:18.224Z  INFO wings: Configuring user pterodactyl (id: 999) as the owner of all server files.
04:11:18.227Z  INFO wings: Configuring timezone file location...
04:11:18.228Z  INFO wings: Checking container networking environment...
04:11:18.232Z  INFO wings: Found network interface for daemon: pterodactyl_nw
04:11:18.233Z  INFO wings: Ensuring correct network interface for containers...
04:11:18.240Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
04:11:18.241Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
04:11:18.262Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: Error while attempting to fetch list of Eggs from the panel.
        at Request._callback (/srv/daemon/src/controllers/service.js:95:31)
        at Request.self.callback (/srv/daemon/node_modules/request/request.js:185:22)
        at Request.emit (events.js:314:20)
        at Request.EventEmitter.emit (domain.js:486:12)
        at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1157:10)
        at Request.emit (events.js:314:20)
        at Request.EventEmitter.emit (domain.js:486:12)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1079:12)
        at Object.onceWrapper (events.js:420:28)
        at IncomingMessage.emit (events.js:326:22)
    --
    additional: {
      "responseCode": 500,
      "requestURL": "http://XXX.XXX.XXX/api/remote/eggs"
    }
04:11:18.262Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.```

**Comment by DaneEveritt** [comment]
That is an issue with your panel, and not the daemon. Additionally it is almost certainly a bug with your configuration, and not anything that can be fixed with code. Please use discord for further assistance before opening a new issue about this. 👍

**Comment by hansputera** [comment]
how to fix this?

**Comment by hansputera** [comment]
i need your attention
