### ISSUE TITLE
Request failed with status code 504 and context deadline exceeded

### ISSUE THREAD

**Issue by Lele991** [pterodactyl/panel#2655]
* Panel or Daemon: Both
* Version of Panel/Daemon: 1.0.3
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 - Google Chrome

**Describe the bug**
* Error 1) At the first start of the panel daemon from this error, to "fix" it you have to restart the daemon:
```
DEBUG: [Nov  3 08:43:24.704] making request to external HTTP endpoint endpoint=https://DOMAIN/api/remote/servers headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer IbMRfqXP(redacted)] Content-Type:[application/json]] method=GET
FATAL: [Nov  3 08:43:54.705] failed to load server configurations error=Get "https://DOMAIN/api/remote/servers": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Stacktrace:
github.com/pterodactyl/wings/server.LoadDirectory
	/home/runner/work/wings/wings/server/loader.go:38
github.com/pterodactyl/wings/cmd.rootCmdRun
	/home/runner/work/wings/wings/cmd/root.go:164
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
```
* Error 2) In the google console this error appears (see the screen):
```
GET https://DOMAIN/api/client/servers/6a8e817e-e3cb-4f9e-b5a2-4ec80b453306/resources 504
Error: Request failed with status code 504
    at e.exports (bundle.d469b6c8.js:1)
    at e.exports (bundle.d469b6c8.js:1)
    at XMLHttpRequest.p.onreadystatechange (bundle.d469b6c8.js:1)
```

**Additional information:**
Panel: `7.4.11`
Daemon: `Linux DE-1 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux` 

**To Reproduce**
1. Go to 'server list'
2. Show console log of browser
![Screenshot_2](https://user-images.githubusercontent.com/6428751/98000250-99843d80-1dec-11eb-9f52-15b2d891b213.png)

**Comment by parkervcp** [comment]
Is #2653 not the same?

**Comment by Lele991** [comment]
Yes, sorry i don't see the issue.. we were talking about it on discord and we probably opened it at the same time

**Comment by Lele991** [comment]
Error on laravel.log of panel (when on console of google appears the error mentioned above):
```
[2020-11-03 16:36:30] production.WARNING: GuzzleHttp\Exception\ConnectException: cURL error 28: Resolving timed out after 3000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/panel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
Stack trace:
#0 /var/www/panel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /var/www/panel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /var/www/panel/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
#3 /var/www/panel/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /var/www/panel/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /var/www/panel/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /var/www/panel/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /var/www/panel/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /var/www/panel/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /var/www/panel/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 /var/www/panel/vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\HandlerStack->__invoke()
#11 /var/www/panel/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\Client->transfer()
#12 /var/www/panel/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync()
#13 /var/www/panel/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\Client->request()
#14 /var/www/panel/app/Repositories/Wings/DaemonServerRepository.php(23): GuzzleHttp\Client->__call()
#15 /var/www/panel/app/Http/Controllers/Api/Client/Servers/ResourceUtilizationController.php(41): Pterodactyl\Repositories\Wings\DaemonServerRepository->getDetails()
#16 [internal function]: Pterodactyl\Http\Controllers\Api\Client\Servers\ResourceUtilizationController->__invoke()
#17 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#18 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#19 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch()
#20 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#21 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#22 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#23 /var/www/panel/app/Http/Middleware/Api/Client/Server/AuthenticateServerAccess.php(84): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\Client\Server\AuthenticateServerAccess->handle()
#25 /var/www/panel/app/Http/Middleware/Api/AuthenticateIPAccess.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\AuthenticateIPAccess->handle()
#27 /var/www/panel/app/Http/Middleware/Api/AuthenticateKey.php(82): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\AuthenticateKey->handle()
#29 /var/www/panel/app/Http/Middleware/Api/ApiSubstituteBindings.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/panel/app/Http/Middleware/Api/Client/SubstituteClientApiBindings.php(60): Pterodactyl\Http\Middleware\Api\ApiSubstituteBindings->handle()
#31 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\Client\SubstituteClientApiBindings->handle()
#32 /var/www/panel/app/Http/Middleware/Api/IsValidJson.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\IsValidJson->handle()
#34 /var/www/panel/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle()
#36 /var/www/panel/app/Http/Middleware/Api/SetSessionDriver.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\SetSessionDriver->handle()
#38 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#40 /var/www/panel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/panel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#42 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#43 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then()
#45 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
#46 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
#47 /var/www/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
#48 /var/www/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
#49 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#50 /var/www/panel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#52 /var/www/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#54 /var/www/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#56 /var/www/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#58 /var/www/panel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#60 /var/www/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#62 /var/www/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 /var/www/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
#64 /var/www/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#65 /var/www/panel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#66 {main}  

```
