### ISSUE TITLE
Server does not restart on "hard crash"

### ISSUE THREAD

**Issue by SecretlyJealous** [pterodactyl/panel#2668]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: CentOS 7
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
There's a scenario (in my case this happens at least once a week) where the server will crash and the panel won't automatically restart it. I have to manually press stop, kill and then start to make the server boot up again.
Crash log: https://paste.gg/p/anonymous/6b794493281d4f88a68e4f272d515a45

At the end of the log there is this error explaining that the main thread was terminated due to a hard crash:
```
[23:40:12] [Paper Watchdog Thread/INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[23:40:12] [Server thread/ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:940) [?:?]
	at net.minecraft.server.v1_16_R2.MinecraftServer.stop(MinecraftServer.java:761) ~[patched_1.16.3.jar:git-Paper-"1916ab2b"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.stop(DedicatedServer.java:698) ~[patched_1.16.3.jar:git-Paper-"1916ab2b"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.close(MinecraftServer.java:735) ~[patched_1.16.3.jar:git-Paper-"1916ab2b"]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.16.3.jar:git-Paper-"1916ab2b"]
[23:40:12] [Paper Watchdog Thread/INFO]: Stopping server
```

**To Reproduce**
1. I'm not sure how to trigger a hard crash on purpose, in this scenario the server is just stuck dealing with lighting updates

**Expected behavior**
The server should reboot in scenarios where a hard crash occurs.

**Comment by GravityCube** [comment]
I think that paper isnt fully stopping the server after crash. In that case you should report that to PaperMC

**Comment by DaneEveritt** [comment]
We don't detect process hanging which is what is happening there. It says stopping but never stops, so to Wings the server container is still running. Crash detection only triggers if the container itself stops.
