### ISSUE TITLE
mounts still dont seem to work

### ISSUE THREAD

**Issue by MilkMGN** [pterodactyl/panel#2723]
all info in #2721 
looked through @matthewpi 's comment, assigned my mount to be in /map/mg on ptero's fs and point to /var/www/map_mg on the linux fs, but no dice.
![image](https://user-images.githubusercontent.com/42798255/99475497-64eeb500-299a-11eb-8929-d57a84064a9e.png)

Dynmaps error:

```[02:24:14 ERROR]: [dynmap] Exception while writing JSON-file - /map/mg/standalone/dynmap_world.json.new
java.io.FileNotFoundException: /map/mg/standalone/dynmap_world.json.new (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_275]
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[?:1.8.0_275]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[?:1.8.0_275]
        at org.dynmap.storage.MapStorage.setStandaloneFile(MapStorage.java:272) ~[?:?]
        at org.dynmap.JsonFileClientUpdateComponent$FileProcessor.run(JsonFileClientUpdateComponent.java:88) ~[?:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) ~[?:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[02:24:14 ERROR]: [dynmap] Exception while writing JSON-file - dynmap_world.json
[02:24:14 INFO]: [dynmap] Image file /map/mg/tiles/_markers_/basket.png - unable to write - failed
```

**Comment by MilkMGN** [comment]
also, i did add it to `allowed_mounts` in config.yml

**Comment by DaneEveritt** [comment]
Stop spamming our issue tracker with issues when we close them.
