### ISSUE TITLE
Backups failing due to archive/tar: write too long causing panic and wings crash

### ISSUE THREAD

**Issue by alliraine** [pterodactyl/panel#2724]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.1.1
* Server's OS: Debian 10.4
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
When creating a backup, mainly of a large server (this one was about 40GB) you get the following error followed by wings crashing and rebooting. https://paste.dedimc.io/rigabekomu.sql
```

Nov 18 15:50:28 US-NY-05-3900X wings[20125]: ERROR: [Nov 18 15:50:28.350] failed to generate backup for server error=backup: error while generating server backup: archive/tar: write too long server=278faecc-8d7d-4cba-88e6-d4d49a970cc3
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: panic: interface conversion: *errors.withMessage is not cli.tracer: missing method StackTrace
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: goroutine 44033 [running]:
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: github.com/pterodactyl/wings/loggers/cli.getErrorStack(0x1181f40, 0xc0002ca0e0, 0xc000a36001, 0x49, 0x1181f40, 0xc0002ca0e0)
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/work/wings/wings/loggers/cli/cli.go:91 +0xb9
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: github.com/pterodactyl/wings/loggers/cli.getErrorStack(0x1181f40, 0xc0002ca080, 0x0, 0x0, 0x0, 0x0)
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/work/wings/wings/loggers/cli/cli.go:94 +0x152
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: github.com/pterodactyl/wings/loggers/cli.(*Handler).HandleLog(0xc000287780, 0xc000250150, 0x0, 0x0)
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/work/wings/wings/loggers/cli/cli.go:76 +0x61a
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: github.com/apex/log/handlers/multi.(*Handler).HandleLog(0xc0002866a0, 0xc000250150, 0x10512ad, 0x24)
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/handlers/multi/multi.go:26 +0x6f
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: github.com/apex/log.(*Logger).log(0x17d97d0, 0x3, 0xc000250070, 0x10512ad, 0x24)
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/logger.go:146 +0x7c
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: github.com/apex/log.(*Entry).Error(...)
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/entry.go:96
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: github.com/pterodactyl/wings/router.postServerBackup.func1(0x11a3140, 0xc000c0c150, 0xc0001e0c80)
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/work/wings/wings/router/router_server_backup.go:43 +0x145
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: created by github.com/pterodactyl/wings/router.postServerBackup
Nov 18 15:50:28 US-NY-05-3900X wings[20125]: #011/home/runner/work/wings/wings/router/router_server_backup.go:41 +0x29b
Nov 18 15:50:28 US-NY-05-3900X systemd[1]: wings.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 18 15:50:28 US-NY-05-3900X systemd[1]: wings.service: Failed with result 'exit-code'.
Nov 18 15:50:28 US-NY-05-3900X systemd[1]: wings.service: Service RestartSec=100ms expired, scheduling restart.
Nov 18 15:50:28 US-NY-05-3900X systemd[1]: wings.service: Scheduled restart job, restart counter is at 1.
Nov 18 15:50:28 US-NY-05-3900X systemd[1]: Stopped Pterodactyl Wings Daemon.
Nov 18 15:50:28 US-NY-05-3900X systemd[1]: Started Pterodactyl Wings Daemon.

```
**To Reproduce**
Create a large Minecraft server and try to back it up. I will be continuing to try to narrow this down further over the next day or two. Any thoughts would be appreciated at this point.

**Expected behavior**
A backup to be created.

**Comment by notAreYouScared** [comment]
Is the server running? If it is, does stopping it and making a backup work? Could you stop wings and start it in debug mode `wings --debug`, try again and post the logs from that?

**Comment by alliraine** [comment]
Yeah, the server is running. I will try to do that tonight or tomorrow. :)

**Comment by alliraine** [comment]
This is going to be a duplicate of issue #2068
