### ISSUE TITLE
A complete html tag in a file gives 500 errors when you try to access.

### ISSUE THREAD

**Issue by SpicyTakis** [pterodactyl/panel#2886]
**Background (please complete the following information):**
* Panel or Daemon: Panel 
* Version of Panel/Daemon: 1.1.3
* Server's OS: Ubuntu 20.04.1
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
If a html file has a completed html tag in it, if you try reloading the file it returns a 500 error.

**To Reproduce**
1. Go to any server
2. Create a new file
3. Add 2 html tags to the file (<html>)
4. Save the file 
5. Reload the page
6. Panel shows 500 error

![image](https://user-images.githubusercontent.com/67237931/102561203-18ce8780-40a2-11eb-82ba-11799096378e.png)

**Expected behavior**
What should happen is when you click on the file it should show the contents of the file.

**Comment by trenutoo** [comment]
Can you provide the file that you are using to reproduce this issue?

I tried a couple of different HTML files and boilerplates without experiencing any similar problem.

**Comment by SpicyTakis** [comment]
it is just 2 simple html tags
```
<html>
<html>
```
https://ptero.co/gipobaheje.apache
This doesnt give a error in wings or the Laravel logs.

**Comment by trenutoo** [comment]
> it is just 2 simple html tags
> 
> ```
> <html>
> <html>
> ```
> 
> This doesnt give a error in wings or the Laravel logs.

I am unable to replicate this on 1.1.3, I tried many boilerplates, actual HTML websites, and the HTML tags themselves which you provided. Each time the file did not cause any errors and functioned as it should

**Comment by DaneEveritt** [comment]
I too cannot reproduce this issue.

**Comment by sn8to** [comment]
~~This issue seems to happen with panel 1.1.3 and daemon 1.1.1. I can't seem to figure out why it only errors with HTML files and not all files, but I'll definitely get in touch with the person responsible for keeping that node updated on why they haven't updated after nearly 2 weeks.~~

Well this is interesting, it is indeed happening with panel 1.1.3 and daemon 1.1.3. I have completely no idea how to reproduce this issue, and both the panel and the daemon don't have any error logs for this issue at all.

**Comment by sn8to** [comment]
Trying to read one of the html files from the API also results in a 500:

![Screenshot of Postman making an API request](https://user-images.githubusercontent.com/17860556/102628466-56b5c500-410f-11eb-80c6-0599ee6f3356.png)

**Comment by DaneEveritt** [comment]
Check your panel error logs in `storage/logs` within the root panel directory.

**Comment by sn8to** [comment]
I already checked them, there's nothing logged at all related to these issues.

**Comment by GlitchMasta47** [comment]
I was finally able to get *some* error logs, but I'm not quite sure if they're useful or related:
```
[2020-12-18 19:51:52] production.ERROR: Predis\Connection\ConnectionException: Connection refused [tcp://localhost:6379] in /var/www/pterodactyl/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /var/www/pterodactyl/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError()
#1 /var/www/pterodactyl/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket()
#2 /var/www/pterodactyl/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer()
#3 /var/www/pterodactyl/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 /var/www/pterodactyl/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\Connection\AbstractConnection->connect()
#5 /var/www/pterodactyl/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\Connection\StreamConnection->connect()
#6 /var/www/pterodactyl/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\Connection\AbstractConnection->getResource()
#7 /var/www/pterodactyl/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\Connection\StreamConnection->write()
#8 /var/www/pterodactyl/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\Connection\StreamConnection->writeRequest()
#9 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(331): Predis\Connection\AbstractConnection->executeCommand()
#10 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand()
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\Client->__call()
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\Redis\Connections\Connection->command()
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(54): Illuminate\Redis\Connections\Connection->__call()
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\Cache\RedisStore->get()
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(374): Illuminate\Cache\Repository->get()
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(383): Illuminate\Cache\Repository->remember()
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call()
#18 /var/www/pterodactyl/app/Providers/AppServiceProvider.php(77): Illuminate\Support\Facades\Facade::__callStatic()
#19 /var/www/pterodactyl/app/Providers/AppServiceProvider.php(30): Pterodactyl\Providers\AppServiceProvider->versionData()
#20 [internal function]: Pterodactyl\Providers\AppServiceProvider->boot()
#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#26 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\Container\Container->call()
#27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\Foundation\Application->bootProvider()
#28 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#29 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk()
#30 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#31 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith()
#33 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\Console\Kernel->bootstrap()
#34 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#35 {main}  
```

**Comment by sn8to** [comment]
this seems to be related to #2603
