### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#2929]
**Background (please complete the following information):**
* Panel or Daemon: 
Daemon
* Version of Panel/Daemon: 
Newest
* Server's OS: 
Ubuntu 18.04
* Your Computer's OS & Browser: 

**Describe the bug**
```Dec 28 23:13:00  wings[7375]:  INFO: [Dec 28 23:13:00.644] syncing server configuration with panel server=3b9e7cd9-bb2f-4ad7-9b6c-495cf8785118
Dec 28 23:13:00  wings[7375]:  INFO: [Dec 28 23:13:00.771] performing server limit modification on-the-fly server=3b9e7cd9-bb2f-4ad7-9b6c-495cf8785118
Dec 28 23:13:02  wings[7375]: {"status":"Pulling from parkervcp/pterodactyl-images","id":"game_samp"}
Dec 28 23:13:02  wings[7375]: {"status":"Digest: sha256:9d4a768abbdd6c64bbfcd6c031ec1cf5449815c3b241e01c8f967d7507bd3ada"}
Dec 28 23:13:02  wings[7375]: {"status":"Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:game_samp"}
Dec 28 23:13:30  wings[7375]: 2020/12/28 23:13:30 http: TLS handshake error from 168.181.254.99:46753: EOF
Dec 28 23:13:37  wings[7375]: 2020/12/28 23:13:37 http: TLS handshake error from 189.84.126.245:46754: EOF
Dec 28 23:14:04  wings[7375]: panic: runtime error: slice bounds out of range [1:0]
Dec 28 23:14:04  wings[7375]: goroutine 228778 [running]:
Dec 28 23:14:04  wings[7375]: github.com/pkg/sftp.recvPacket(0x1181fa0, 0xc0146f72c0, 0x29, 0x29, 0x118e280, 0xc0132d3140, 0x0, 0x0)
Dec 28 23:14:04  wings[7375]: #011/home/runner/go/pkg/mod/github.com/pkg/sftp@v1.11.0/packet.go:162 +0x226
Dec 28 23:14:04  wings[7375]: github.com/pkg/sftp.(*conn).recvPacket(...)
Dec 28 23:14:04  wings[7375]: #011/home/runner/go/pkg/mod/github.com/pkg/sftp@v1.11.0/conn.go:22
Dec 28 23:14:04  wings[7375]: github.com/pkg/sftp.(*RequestServer).Serve(0xc008f8f800, 0x0, 0x0)
Dec 28 23:14:04  wings[7375]: #011/home/runner/go/pkg/mod/github.com/pkg/sftp@v1.11.0/request-server.go:110 +0x1ab
Dec 28 23:14:04  wings[7375]: github.com/pterodactyl/wings/sftp.Server.AcceptInboundConnection(0xc00d5873a0, 0xc0001af0e0, 0x1c, 0x0, 0x7e6, 0xc0002e6090, 0x7, 0x3e7, 0x3e7, 0x107cb98, ...)
Dec 28 23:14:04  wings[7375]: #011/home/runner/work/wings/wings/sftp/server.go:178 +0x373
Dec 28 23:14:04  wings[7375]: created by github.com/pterodactyl/wings/sftp.(*Server).Initialize
Dec 28 23:14:04  wings[7375]: #011/home/runner/work/wings/wings/sftp/server.go:118 +0x592
Dec 28 23:14:04  systemd[1]: wings.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 28 23:14:04  systemd[1]: wings.service: Failed with result 'exit-code'.
Dec 28 23:14:04  systemd[1]: wings.service: Service hold-off time over, scheduling restart.
Dec 28 23:14:04  systemd[1]: wings.service: Scheduled restart job, restart counter is at 2.
```

server crashed why ?

**To Reproduce**
1. Install everything
2. Host > 2k servers 
3. Wait some time and this happened

**Expected behavior**
No server crash ?

**Comment by RihanArfan** [comment]
I think the issue has something to do with reproduction step 2.

**Comment by matthewpi** [comment]
Unless you can provide decent reproduction steps with more information and that doesn't involve running thousands of servers, I don't plan on spending any time investigating this.

**Comment by BenasPaulikas** [comment]
Makes sense created related question about limits on https://github.com/pterodactyl/panel/discussions/2933
