### ISSUE TITLE
Using server backups causes Wings & panel to crash and burn

### ISSUE THREAD

**Issue by UP934387** [pterodactyl/panel#3135]
this is likely related to https://github.com/pterodactyl/panel/issues/2068 but there doesn't seem to be any kind of recovery guide

**Background (please complete the following information):**
* Panel or Daemon:  Panel & Wings 
* Version of Panel/Daemon: 1.2.3
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10 & Firefox

**Describe the bug**
Attempted to backup server, server was running had dynmap coreprotect oneplayersleep. panel froze webpage stopped responding. box was rebooted. wings and panel are not able to come online
https://ptero.co/topogazode

**To Reproduce**
1. back up server that is running
2. Pterodactyl will now no longer boot

**Expected behavior**
for Pterodactyl not to crash and burn.

**Comment by UP934387** [comment]
root@mserver1:/home/mserver# tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log
```
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#17 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))[2021-03-02 17:39:01] production.NOTICE: A query exception was encountered while trying to load settings from the database: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `settings`)
[2021-03-02 17:39:01] production.ERROR: Predis\Response\ServerException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. in /var/www/pterodactyl/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\StringSetExpire), Object(Predis\Response\Error))
#1 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\StringSetExpire))
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\Client->__call('setex', Array)
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\Redis\Connections\Connection->command('setex', Array)
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(93): Illuminate\Redis\Connections\Connection->__call('setex', Array)
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(211): Illuminate\Cache\RedisStore->put('git-version', Array, 5)
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(383): Illuminate\Cache\Repository->put('git-version', Array, 5)
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(383): Illuminate\Cache\Repository->remember('git-version', 5, Object(Closure))
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call('remember', Array)
#9 /var/www/pterodactyl/app/Providers/AppServiceProvider.php(77): Illuminate\Support\Facades\Facade::__callStatic('remember', Array)
#10 /var/www/pterodactyl/app/Providers/AppServiceProvider.php(30): Pterodactyl\Providers\AppServiceProvider->versionData()
#11 [internal function]: Pterodactyl\Providers\AppServiceProvider->boot()
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\Container\Container->call(Array)
#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\Foundation\Application->bootProvider(Object(Pterodactyl\Providers\AppServiceProvider))
#19 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Pterodactyl\Providers\AppServiceProvider), 23)
#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith(Array)
#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\Console\Kernel->bootstrap()
#25 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
[2021-03-02 17:39:04] production.ERROR: Predis\Response\ServerException: ERR Error running script (call to f_230148430cb441a76f6486ae084405a674e00385): @user_script:2: @user_script: 2: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.    in /var/www/pterodactyl/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\ServerEval), Object(Predis\Response\Error))
#1 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\ServerEval))
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\Client->__call('eval', Array)
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\Redis\Connections\Connection->command('eval', Array)
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(223): Illuminate\Redis\Connections\Connection->__call('eval', Array)
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(169): Illuminate\Queue\RedisQueue->retrieveNextJob('queues:high')
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(282): Illuminate\Queue\RedisQueue->pop('high')
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(121): Illuminate\Queue\Worker->getNextJob(Object(Illuminate\Queue\RedisQueue), 'high')
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'high,standard,l...', Object(Illuminate\Queue\WorkerOptions))
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,standard,l...')
#10 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#17 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))[2021-03-02 17:40:01] production.NOTICE: A query exception was encountered while trying to load settings from the database: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `settings`)
[2021-03-02 17:40:01] production.ERROR: Predis\Response\ServerException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. in /var/www/pterodactyl/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\StringSetExpire), Object(Predis\Response\Error))
#1 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\StringSetExpire))
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\Client->__call('setex', Array)
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\Redis\Connections\Connection->command('setex', Array)
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(93): Illuminate\Redis\Connections\Connection->__call('setex', Array)
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(211): Illuminate\Cache\RedisStore->put('git-version', Array, 5)
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(383): Illuminate\Cache\Repository->put('git-version', Array, 5)
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(383): Illuminate\Cache\Repository->remember('git-version', 5, Object(Closure))
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call('remember', Array)
#9 /var/www/pterodactyl/app/Providers/AppServiceProvider.php(77): Illuminate\Support\Facades\Facade::__callStatic('remember', Array)
#10 /var/www/pterodactyl/app/Providers/AppServiceProvider.php(30): Pterodactyl\Providers\AppServiceProvider->versionData()
#11 [internal function]: Pterodactyl\Providers\AppServiceProvider->boot()
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\Container\Container->call(Array)
#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\Foundation\Application->bootProvider(Object(Pterodactyl\Providers\AppServiceProvider))
#19 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Pterodactyl\Providers\AppServiceProvider), 23)
#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith(Array)
#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\Console\Kernel->bootstrap()
#25 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
[2021-03-02 17:40:04] production.ERROR: Predis\Response\ServerException: ERR Error running script (call to f_230148430cb441a76f6486ae084405a674e00385): @user_script:2: @user_script: 2: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.    in /var/www/pterodactyl/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\ServerEval), Object(Predis\Response\Error))
#1 /var/www/pterodactyl/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\ServerEval))
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\Client->__call('eval', Array)
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\Redis\Connections\Connection->command('eval', Array)
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(223): Illuminate\Redis\Connections\Connection->__call('eval', Array)
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(169): Illuminate\Queue\RedisQueue->retrieveNextJob('queues:high')
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(282): Illuminate\Queue\RedisQueue->pop('high')
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(121): Illuminate\Queue\Worker->getNextJob(Object(Illuminate\Queue\RedisQueue), 'high')
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'high,standard,l...', Object(Illuminate\Queue\WorkerOptions))
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,standard,l...')
#10 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#17 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))root@mserver1:/home/mserver#

```

**Comment by trenutoo** [comment]
That laravel error looks like you don't have enough space left. What's the output of `df -h`?

**Comment by DaneEveritt** [comment]
This has nothing to do with this software, the error is pretty clear that you're out of disk space.

```
[2021-03-02 17:40:04] production.ERROR: Predis\Response\ServerException: ERR Error running script (call to f_230148430cb441a76f6486ae084405a674e00385): @user_script:2: @user_script: 2: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.    in /var/www/pterodactyl/vendor/predis/predis/src/Client.php:370
```

** [...] currently not able to persist on disk**

**Please check the Redis logs for details about the RDB error** :)

**Comment by UP934387** [comment]
thats not good. its just filled up 3.5TB of space. the servers installed very much do not total 3.5TB there's only 3 mc server which have about 40GB allocated total

**Comment by UP934387** [comment]
![image](https://user-images.githubusercontent.com/72730380/109693451-940fe780-7b81-11eb-9ee7-5f636be5782c.png)
this is the disk pterodactyl is using for servers 44% disk used

**Comment by UP934387** [comment]
![image](https://user-images.githubusercontent.com/72730380/109694067-4778dc00-7b82-11eb-943f-f8ed293106d2.png)

**Comment by DaneEveritt** [comment]
Its not Pterodactyl using disk space, the error is coming from Redis.
