### ISSUE TITLE
Error during create Minecraft server Unexpected tokens =

### ISSUE THREAD

**Issue by lukeskymc** [Pterodactyl/Panel#348]
Hello, 

When I create a Minecraft server from the pterodactyl panel, after the installation of the node and configuration. I have this error in node server with daemon : 
```
20:55:51.856Z  INFO wings: SFTP container successfully booted.
20:55:51.860Z  INFO wings: Attempting to load servers and initialize daemon...
20:55:51.885Z FATAL wings: A fatal error occured during an operation.
    SyntaxError: Unexpected token =
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Function.<anonymous> (/srv/daemon/node_modules/rfr/lib/rfr.js:160:12)
        at Object.<anonymous> (/srv/daemon/src/services/minecraft/index.js:28:14)
        at Module._compile (module.js:409:26)
20:55:52.042Z  INFO wings: Pterodactyl Daemon is up-to-date!
```
I made some searches, and people says to reinstall node.js so I made it, but no changement. 
I already reinstalled docker and daemon. 

Thank you for your help, and keep up the good work.

**Comment by DaneEveritt** [comment]
What version of Nodejs do you have installed?

**Comment by lukeskymc** [comment]
Thank you for your answer. 
Nodejs and npm versions: 

/srv/daemon# node -v
v6.9.1
/srv/daemon# npm -v
4.4.1

I tried to delete the folder "node_modules" and reinstalled Nodejs, now I have this issue : 

12:36:09.249Z  INFO wings: Loading modules, this could take a few seconds.
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/daemon/node_modules/mmmagic/lib/index.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

Which version of Nodejs I need to use exactly ?

**Comment by DaneEveritt** [comment]
I'll need to look into that later today, it's always been an issue with mmmagic especially when they are V8 engine updates.

**Comment by DaneEveritt** [comment]
https://github.com/Pterodactyl/Daemon/commit/24123aee00a2ad1854da197b0934d2c9dbe74268 removes `mmmagic` as a dependency.
