### ISSUE TITLE
don't open the server

### ISSUE THREAD

**Issue by AlfredRobson** [pterodactyl/panel#3745]
### Is there an existing issue for this?

- [ ] I have searched the existing issues before opening this issue.

### Current Behavior

don't open the server

### Expected Behavior

he open

### Steps to Reproduce

Click start

### Panel Version

1.4.0

### Wings Version

1.4.2

### Error Logs

```bash
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
Java 8 detectado, iniciando servidor...
enxada@host:/home/container$ java-8 -Duser.timezone=America/Sao_Paulo -Xms128M -Xmx5120M -jar forge-server.jar -Dfml.readTimeout=60
[18:04:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.4, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, -Dfml.readTimeout=60]
[18:04:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_302 by Oracle Corporation
[18:04:28] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:04:28] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/container/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[18:04:34] [main/ERROR] [mixin/]: Mixin config mostructures.mixins.json does not specify "minVersion" property
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [org.infernalstudios.infernalexp.mixin.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [tictim.paraglider.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [shetiphian.core.mixins.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.meteor.extrabotany.common.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.leobeliik.extremesoundmuffler.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [de.maxhenkel.miningdimension.mixin.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [thelm.jaopca.mixins.JAOPCAMixinConnector]
[18:04:35] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[18:04:35] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., -Dfml.readTimeout=60]
[18:04:35] [main/WARN] [mixin/]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[18:04:35] [main/WARN] [mixin/]: Reference map 'nethers_delight.refmap.json' for nethers_delight.mixins.json could not be read. If this is a development environment you can ignore this message
[18:04:35] [main/WARN] [mixin/]: Reference map 'hackforge.refmap.json' for creategears.mixins.json could not be read. If this is a development environment you can ignore this message
[18:04:35] [main/INFO] [co.pe.co.Performant/]: Performant configs loaded
[18:04:36] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_custom_entity_collision' ASM patch...
[18:04:36] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_custom_entity_collision' ASM patch!
[18:04:36] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'reach_set_server_entity_interact' ASM patch...
[18:04:36] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'reach_set_server_entity_interact' ASM patch!
[18:04:36] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'allow_entity_interaction' ASM patch...
[18:04:36] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'allow_entity_interaction' ASM patch!
[HammerLib] Transforming ServerPlayNetHandler!
[HammerLib] Tapping into sendPacket (func_211148_a)
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'set_player_field' ASM patch...
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'set_player_field' ASM patch!
[18:04:37] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'water_movement_slowdown_prevention' ASM patch...
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'water_movement_slowdown_prevention' ASM patch!
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_levels' ASM patch...
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_levels' ASM patch!
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_enchantments' ASM patch...
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_enchantments' ASM patch!
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_apply_modifier' ASM patch...
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_apply_modifier' ASM patch!
[18:04:37] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/IngameGui for invalid dist DEDICATED_SERVER
[18:04:37] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/IngameGui (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/IngameGui for invalid dist DEDICATED_SERVER)
[18:04:37] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.IngameGui was not found conjuring.mixins.json:InGameHudMixin
[18:04:37] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/ItemRenderer for invalid dist DEDICATED_SERVER
[18:04:37] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/ItemRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/ItemRenderer for invalid dist DEDICATED_SERVER)
[18:04:37] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.ItemRenderer was not found conjuring.mixins.json:ItemRendererMixin
[18:04:37] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_missing_tag_enchantment_tooltip' ASM patch...
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_missing_tag_enchantment_tooltip' ASM patch!
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_tooltip' ASM patch...
[18:04:37] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_tooltip' ASM patch!
[18:04:38] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'render_particles' ASM patch...
[18:04:38] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'render_particles' ASM patch!
[18:04:38] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/particle/ParticleManager for invalid dist DEDICATED_SERVER
[18:04:38] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/particle/ParticleManager (java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleManager for invalid dist DEDICATED_SERVER)
[18:04:38] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.particle.ParticleManager was not found conjuring.mixins.json:ParticleManagerAccessor
[18:04:38] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
[18:04:38] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/WorldRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER)
[18:04:38] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.WorldRenderer was not found conjuring.mixins.json:SpawnerParticleMixin
[18:04:38] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
[18:04:38] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/WorldRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER)
[18:04:38] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.WorldRenderer was not found conjuring.mixins.json:WorldRendererMixin
[18:04:38] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[18:04:38] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER)
[18:04:38] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found ars_nouveau.mixins.json:ClientElytraMixin
[18:04:39] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching DataPackRegistries#<init>
[18:04:39] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[18:04:39] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[18:04:39] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'sun_brightness_server' ASM patch...
[18:04:39] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'sun_brightness_server' ASM patch!
[18:04:39] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LootTableManager#apply
[18:04:40] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[18:04:40] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[18:04:40] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[18:04:40] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'post_process_vanilla' ASM patch...
[18:04:40] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'post_process_vanilla' ASM patch!
[18:04:41] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: D is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[jopt-simple-5.0.4.jar:?] {}
        at net.minecraft.server.Main.main(Main.java:78) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-server.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-server.jar:?] {}
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
Java 8 detectado, iniciando servidor...
enxada@host:/home/container$ java-8 -Duser.timezone=America/Sao_Paulo -Xms128M -Xmx5120M -jar forge-server.jar -Dfml.readTimeout=60
[18:04:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.4, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, -Dfml.readTimeout=60]
[18:04:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_302 by Oracle Corporation
[18:04:46] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:04:47] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/container/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[18:04:53] [main/ERROR] [mixin/]: Mixin config mostructures.mixins.json does not specify "minVersion" property
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [org.infernalstudios.infernalexp.mixin.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [tictim.paraglider.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [shetiphian.core.mixins.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.meteor.extrabotany.common.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.leobeliik.extremesoundmuffler.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [de.maxhenkel.miningdimension.mixin.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [thelm.jaopca.mixins.JAOPCAMixinConnector]
[18:04:53] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[18:04:54] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., -Dfml.readTimeout=60]
[18:04:54] [main/WARN] [mixin/]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[18:04:54] [main/WARN] [mixin/]: Reference map 'nethers_delight.refmap.json' for nethers_delight.mixins.json could not be read. If this is a development environment you can ignore this message
[18:04:54] [main/WARN] [mixin/]: Reference map 'hackforge.refmap.json' for creategears.mixins.json could not be read. If this is a development environment you can ignore this message
[18:04:54] [main/INFO] [co.pe.co.Performant/]: Performant configs loaded
[18:04:54] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_custom_entity_collision' ASM patch...
[18:04:54] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_custom_entity_collision' ASM patch!
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'reach_set_server_entity_interact' ASM patch...
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'reach_set_server_entity_interact' ASM patch!
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'allow_entity_interaction' ASM patch...
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'allow_entity_interaction' ASM patch!
[HammerLib] Transforming ServerPlayNetHandler!
[HammerLib] Tapping into sendPacket (func_211148_a)
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'set_player_field' ASM patch...
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'set_player_field' ASM patch!
[18:04:55] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'water_movement_slowdown_prevention' ASM patch...
[18:04:55] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'water_movement_slowdown_prevention' ASM patch!
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_levels' ASM patch...
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_levels' ASM patch!
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_enchantments' ASM patch...
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_enchantments' ASM patch!
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_apply_modifier' ASM patch...
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_apply_modifier' ASM patch!
[18:04:56] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/IngameGui for invalid dist DEDICATED_SERVER
[18:04:56] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/IngameGui (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/IngameGui for invalid dist DEDICATED_SERVER)
[18:04:56] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.IngameGui was not found conjuring.mixins.json:InGameHudMixin
[18:04:56] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/ItemRenderer for invalid dist DEDICATED_SERVER
[18:04:56] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/ItemRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/ItemRenderer for invalid dist DEDICATED_SERVER)
[18:04:56] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.ItemRenderer was not found conjuring.mixins.json:ItemRendererMixin
[18:04:56] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_missing_tag_enchantment_tooltip' ASM patch...
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_missing_tag_enchantment_tooltip' ASM patch!
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_enchantment_tooltip' ASM patch...
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_enchantment_tooltip' ASM patch!
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'render_particles' ASM patch...
[18:04:56] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'render_particles' ASM patch!
[18:04:56] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/particle/ParticleManager for invalid dist DEDICATED_SERVER
[18:04:56] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/particle/ParticleManager (java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleManager for invalid dist DEDICATED_SERVER)
[18:04:56] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.particle.ParticleManager was not found conjuring.mixins.json:ParticleManagerAccessor
[18:04:56] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
[18:04:56] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/WorldRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER)
[18:04:56] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.WorldRenderer was not found conjuring.mixins.json:SpawnerParticleMixin
[18:04:56] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
[18:04:56] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/WorldRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER)
[18:04:56] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.WorldRenderer was not found conjuring.mixins.json:WorldRendererMixin
[18:04:57] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[18:04:57] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER)
[18:04:57] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found ars_nouveau.mixins.json:ClientElytraMixin
[18:04:57] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching DataPackRegistries#<init>
[18:04:57] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[18:04:57] [main/INFO] [ne.mi.co.Co.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[18:04:57] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'sun_brightness_server' ASM patch...
[18:04:57] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'sun_brightness_server' ASM patch!
[18:04:57] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LootTableManager#apply
[18:04:58] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[18:04:58] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[18:04:58] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[18:04:59] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'post_process_vanilla' ASM patch...
[18:04:59] [main/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'post_process_vanilla' ASM patch!
[18:05:00] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: D is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59) ~[jopt-simple-5.0.4.jar:?] {}
        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[jopt-simple-5.0.4.jar:?] {}
        at net.minecraft.server.Main.main(Main.java:78) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-server.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-server.jar:?] {}
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

**Comment by Jelcoo** [comment]
Firstly, you are using an old version of the panel. Secondly your server crashed. I don't believe this is a problem with the panel

**Comment by trenutoo** [comment]
Your panel and wings version is below the supported one. You should update.

This is not a Pterodactyl-related bug and instead an issue with your Forge server. `D is not a recognized option` which is caused by `-Dfml.readTimeout=60` in your startup args as that parameter doesn't exist anymore.

**Comment by AlfredRobson** [comment]
ok, i'll try, but as i don't know much about the subject i believe i won't make it
I'll wait for the server support I'm paying
