### ISSUE TITLE
Wings Issue

### ISSUE THREAD

**Issue by Minetrax-Network** [pterodactyl/panel#3895]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

After some time of running / making a edit to a server on the node the wings suddenly dies and we have to start them with wings command again.

My os is arc64

### Expected Behavior

It must be up with no flaws / random shutdowns.

### Steps to Reproduce

1. On a panel with a external node.
2. Make a server java 8 server paper 1.8.8
3. Start/Stop it and the error comes

### Panel Version

1.7.0

### Wings Version

1.5.4

### Error Logs

```bash
https://ptero.co/icugumevoj
or
https://ptero.co/ymyjaqiriv
```

**Comment by BenasPaulikas** [comment]
I get this issue too after upgrading wings from 1.5.0 to 1.5.4

I'm 50% confident it happens when wings tries to access non existing files.

```
ERROR: [Jan 20 10:29:54.495] error while listing directory error=open /var/lib/pterodactyl/volumes/58db32d3-d11e-4b1c-b96e-10587b953788/mods/deathmatch/resources/car mod: no such file or directory ip=****:25169 subsystem=sftp username=user_******

Stacktrace:
open /var/lib/pterodactyl/volumes/58db32d3-d11e-4b1c-b96e-10587b953788/mods/deathmatch/resources/car mod: no such file or directory
github.com/pterodactyl/wings/sftp.(*Handler).Filelist
        /home/runner/work/wings/wings/sftp/handler.go:262
github.com/pkg/sftp.(*Request).opendir
        /home/runner/go/pkg/mod/github.com/pkg/sftp@v1.13.2/request.go:268
github.com/pkg/sftp.(*RequestServer).packetWorkerThis issu
        /home/runner/go/pkg/mod/github.com/pkg/sftp@v1.13.2/request-server.go:210
github.com/pkg/sftp.(*RequestServer).Serve.func2.1
        /home/runner/go/pkg/mod/github.com/pkg/sftp@v1.13.2/request-server.go:152
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
```

On 1.5.0 this was fine I got many of them and wings didn't died :)

Once that happens I get

```
panic: send on closed channel

goroutine 6354 [running]:
github.com/pterodactyl/wings/server.(*sinkPool).Push(0xc003d6f890, {0xc002a8b000, 0x0, 0x1000})
        /home/runner/work/wings/wings/server/sink.go:63 +0x158
github.com/pterodactyl/wings/server.(*Server).processConsoleOutputEvent(0xc00417f400, {0xc002a8b000, 0x48844b, 0x1000})
        /home/runner/work/wings/wings/server/listeners.go:86 +0x137
github.com/pterodactyl/wings/environment/docker.(*Environment).scanOutput.func1({0xc002a8b000, 0xc002776dae, 0x2})
        /home/runner/work/wings/wings/environment/docker/container.go:348 +0xba
github.com/pterodactyl/wings/system.ScanReader({0x1027320, 0xc002409480}, 0xc002776f78)
        /home/runner/work/wings/wings/system/utils.go:77 +0x36b
github.com/pterodactyl/wings/environment/docker.(*Environment).scanOutput(0xc001f17a70, {0x1032eb0, 0xc002409480})
        /home/runner/work/wings/wings/environment/docker/container.go:345 +0xc5
created by github.com/pterodactyl/wings/environment/docker.(*Environment).followOutput
        /home/runner/work/wings/wings/environment/docker/container.go:337 +0x225
```

Time for a hotfix hehe

**Comment by RemDey** [comment]
I have the exact same error after updating. 

`panic: send on closed channel`
`goroutine 841 [running]:`
`github.com/pterodactyl/wings/server.(*sinkPool).Push(0x400059a660, {0x40007a1000, 0x31, 0x1000})
   /home/runner/work/wings/wings/server/sink.go:63 +0x140
github.com/pterodactyl/wings/server.(*Server).processConsoleOutputEvent(0x40003d8000, {0x40007a1000, 0x31, 0x1000})
   /home/runner/work/wings/wings/server/listeners.go:86 +0x130
github.com/pterodactyl/wings/environment/docker.(*Environment).scanOutput.func1({0x40007a1000, 0x31, 0x1000})
   /home/runner/work/wings/wings/environment/docker/container.go:348 +0xe0
github.com/pterodactyl/wings/system.ScanReader({0xbf6f60, 0x4000012cc0}, 0x40007f5f98)
   /home/runner/work/wings/wings/system/utils.go:77 +0x380
github.com/pterodactyl/wings/environment/docker.(*Environment).scanOutput(0x40001c8510, {0xc01f70, 0x4000012cc0})
   /home/runner/work/wings/wings/environment/docker/container.go:345 +0x94
created by github.com/pterodactyl/wings/environment/docker.(*Environment).followOutput
   /home/runner/work/wings/wings/environment/docker/container.go:337 +0x1f8`

**Comment by DaneEveritt** [comment]
@matthewpi appears your event listener updates are crashing.

**Comment by matthewpi** [comment]
I'm over it.

https://github.com/pterodactyl/wings/commit/a6b77a31dc6a5a25b558a10738bc2226795f1f4a

You can download the new version from https://github.com/pterodactyl/wings/suites/5002300580/artifacts/146720759 until a new release is pushed.

**Comment by DaneEveritt** [comment]
![Uploading dumpster_fire.gif…]()

**Comment by DaneEveritt** [comment]
![dumpster_fire](https://user-images.githubusercontent.com/418376/150353326-b87af209-ee6a-4002-9a67-55b23dc2aca5.gif)

**Comment by beckylemesmash** [comment]
One more please:

```
Jul 28 10:55:42 Ubuntu-1804-bionic-64-minimal wings[17710]:  INFO: [Jul 28 10:55:42.991] destroying all registered sinks for server instance server=de91c7d0-013b-4f7e-bba3-e4684653b570
Jul 28 10:55:42 Ubuntu-1804-bionic-64-minimal wings[17710]:  WARN: [Jul 28 10:55:42.991] failed to send event to websocket: close already sent event=console output server=de91c7d0-013b-4f7e-bba3-e4684653b570 subsystem=websocket
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: panic: send on closed channel
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: goroutine 106695268 [running]:
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: github.com/pterodactyl/wings/system.(*Locker).Acquire(0xc0070b9280)
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: #011github.com/pterodactyl/wings/system/locker.go:38 +0x6e
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: github.com/pterodactyl/wings/server.(*Server).HandlePowerAction(0xc0045b5b80, {0xc0043eb0ce, 0x5}, {0x0, 0x0, 0x57?})
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: #011github.com/pterodactyl/wings/server/power.go:102 +0x5da
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: github.com/pterodactyl/wings/router/websocket.(*Handler).HandleInbound(0xc00b7ea230, {0x144d000, 0xc0028ea640}, {{0xc0043eb0ba, 0x9}, {0xc005c0d080, 0x1, 0x1}})
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: #011github.com/pterodactyl/wings/router/websocket/websocket.go:363 +0x9f6
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: github.com/pterodactyl/wings/router.getServerWebsocket.func3({{0xc0043eb0ba, 0x9}, {0xc005c0d080, 0x1, 0x1}})
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: #011github.com/pterodactyl/wings/router/router_server_ws.go:85 +0x65
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: created by github.com/pterodactyl/wings/router.getServerWebsocket in goroutine 106693894
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[17710]: #011github.com/pterodactyl/wings/router/router_server_ws.go:84 +0x556
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal systemd[1]: wings.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal systemd[1]: wings.service: Failed with result 'exit-code'.
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal systemd[1]: wings.service: Service hold-off time over, scheduling restart.
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal systemd[1]: wings.service: Scheduled restart job, restart counter is at 6.
Jul 28 10:55:43 Ubuntu-1804-bionic-64-minimal wings[24180]:  INFO: [Jul 28 10:55:43.355] writing log files to disk path=/var/log/pterodactyl/wings.log

```
