### ISSUE TITLE
Cannot change SFTP password

### ISSUE THREAD

**Issue by idkw** [Pterodactyl/Panel#420]
On panel version 0.5.7, when I try to change the SFTP password of a server I get this error message : 

```
There was an error while attmping to contact the remote service to change the password.
```

When i look into the laravel logs I see :

```
[2017-05-02 19:14:48] production.ERROR: GuzzleHttp\Exception\ServerException: Server error: `POST https://km001.hardcraft.fr:8080/server/password` resulted in a `500 Internal Server Error` response:
{
    "error": "(HTTP code 404) no such container - No such container: 19b9686dd9c49a49b55a53b29408b745b94ea969f13ec7616 (truncated...)
 in /var/www/html/panel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /var/www/html/panel/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/html/panel/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/panel/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/html/panel/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/panel/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/html/panel/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/html/panel/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/html/panel/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/html/panel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/panel/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/html/panel/app/Repositories/ServerRepository.php(976): GuzzleHttp\Client->request('POST', '/server/passwor...', Array)
#11 /var/www/html/panel/app/Http/Controllers/Server/ServerController.php(255): Pterodactyl\Repositories\ServerRepository->updateSFTPPassword(2, 'k2GUa9hmhMVC')
#12 [internal function]: Pterodactyl\Http\Controllers\Server\ServerController->postSettingsSFTP(Object(Illuminate\Http\Request), '2caed250')
#13 /var/www/html/panel/bootstrap/cache/compiled.php(9409): call_user_func_array(Array, Array)
#14 /var/www/html/panel/bootstrap/cache/compiled.php(9436): Illuminate\Routing\Controller->callAction('postSettingsSFT...', Array)
#15 /var/www/html/panel/bootstrap/cache/compiled.php(8490): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Pterodactyl\Http\Controllers\Server\ServerController), 'postSettingsSFT...')
#16 /var/www/html/panel/bootstrap/cache/compiled.php(8471): Illuminate\Routing\Route->runController()
#17 /var/www/html/panel/bootstrap/cache/compiled.php(8180): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/panel/bootstrap/cache/compiled.php(3162): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/panel/app/Http/Middleware/CheckServer.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Pterodactyl\Http\Middleware\CheckServer->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/panel/bootstrap/cache/compiled.php(9879): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/panel/bootstrap/cache/compiled.php(8181): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/html/panel/bootstrap/cache/compiled.php(8172): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /var/www/html/panel/bootstrap/cache/compiled.php(8163): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /var/www/html/panel/bootstrap/cache/compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/panel/app/Http/Middleware/LanguageMiddleware.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Pterodactyl\Http\Middleware\LanguageMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/panel/bootstrap/cache/compiled.php(13508): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/panel/bootstrap/cache/compiled.php(11934): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/panel/bootstrap/cache/compiled.php(13254): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/html/panel/bootstrap/cache/compiled.php(13191): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/panel/bootstrap/cache/compiled.php(3224): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/html/panel/vendor/dingo/api/src/Http/Middleware/Request.php(108): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/html/panel/bootstrap/cache/compiled.php(9894): Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/html/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/html/panel/bootstrap/cache/compiled.php(9879): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/html/panel/bootstrap/cache/compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/html/panel/bootstrap/cache/compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 /var/www/html/panel/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#59 {main}
```

**Comment by DaneEveritt** [comment]
Please restart the daemon and repeat the password change, there is a known bug that has been resolved in beta releases.

Let me know if that fixes it.

**Comment by idkw** [comment]
I have restarted the daemon with : 
`sudo service wings restart`
Then I was able to change the SFTP password
Thanks
