### ISSUE TITLE
docker.auth.images missing in daemon documentation

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#437]
Using private registry as described [here ](https://daemon.pterodactyl.io/docs/using-private-registries) lead to authentication refused with 100% working creds.

```
{"name":"wings","hostname":"node.domain.com","pid":18822,"server":"3d362953-dd23-4b95-b1b0-ece3a7c5cd18","level":40,"msg":"Container was not found. Attempting to recreate it.","time":"2017-05-15T18:44:50.891Z","v":0}
{"name":"wings","hostname":"node.domain.com","pid":18822,"level":30,"msg":"Checking if we need to update image hub.domain.com/ptero/docker-csgo:latest, if so it will happen now.","time":"2017-05-15T18:44:50.892Z","v":0}
{"name":"wings","hostname":"node.domain.com","pid":18822,"level":50,"err":{"message":"(HTTP code 500) server error - {\"message\":\"Get https://hub.domain.com/v2/ptero/docker-csgo/manifests/latest: denied: access forbidden\"}\n ","name":"Error","stack":"Error: (HTTP code 500) server error - {\"message\":\"Get https://hub.domain.com/v2/ptero/docker-csgo/manifests/latest: denied: access forbidden\"}\n \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:239:17\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:266:9)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"(HTTP code 500) server error - {\"message\":\"Get https://hub.domain.com/v2/ptero/docker-csgo/manifests/latest: denied: access forbidden\"}\n ","time":"2017-05-15T18:44:51.117Z","v":0}
{"name":"wings","hostname":"node.domain.com","pid":18822,"level":30,"msg":"Notified remote panel of server install status.","time":"2017-05-15T18:44:51.813Z","v":0}
{"name":"wings","hostname":"node.domain.com","pid":18822,"server":"3d362953-dd23-4b95-b1b0-ece3a7c5cd18","level":30,"msg":"Server status has been changed to STARTING","time":"2017-05-15T18:44:51.814Z","v":0}
{"name":"wings","hostname":"node.domain.com","pid":18822,"level":60,"path":"/servers","method":"POST","msg":"TypeError: Cannot read property 'size' of undefined\n    at Async.series.callback (/srv/daemon/src/controllers/server.js:250:24)\n    at /srv/daemon/node_modules/async/dist/async.js:3830:24\n    at replenish (/srv/daemon/node_modules/async/dist/async.js:946:17)\n    at /srv/daemon/node_modules/async/dist/async.js:950:9\n    at eachOfLimit (/srv/daemon/node_modules/async/dist/async.js:975:24)\n    at /srv/daemon/node_modules/async/dist/async.js:980:16\n    at _parallel (/srv/daemon/node_modules/async/dist/async.js:3829:5)\n    at Object.series (/srv/daemon/node_modules/async/dist/async.js:4684:5)\n    at Server.start (/srv/daemon/src/controllers/server.js:246:15)\n    at Request.post [as _callback] (/srv/daemon/src/controllers/routes.js:127:44)","time":"2017-05-15T18:44:51.815Z","v":0}
{"name":"wings","hostname":"node.domain.com","pid":18822,"level":60,"path":"/servers","method":"POST","msg":"TypeError: Cannot read property 'size' of undefined\n    at Timeout.diskUse [as _onTimeout] (/srv/daemon/src/controllers/server.js:452:16)\n    at ontimeout (timers.js:390:18)\n    at tryOnTimeout (timers.js:250:5)\n    at Timer.listOnTimeout (timers.js:214:5)","time":"2017-05-15T18:44:53.815Z","v":0}
```

Once again, using the same creds for manual pull works.

**Comment by jffz** [comment]
Any news about this one ?
#215

**Comment by schrej** [comment]
According to the code `docker.registry.images` needs to be an array of images to use the credentials for.
It should be supporting wildcards with `*` but I assume that's broken at the moment @DaneEveritt (see [here](https://github.com/Pterodactyl/Daemon/commit/69d5d37ddc131b9d3cff91b631b44c48248b0239#diff-677aaccd7b2a4fb21a84b547c866db53L75)).

**Comment by jffz** [comment]
Now working, as you stated @schrej 'docker.registry.images' was missing.

**Comment by DaneEveritt** [comment]
This is not a bug, simply needs someone to submit some documentation changes.
