### ISSUE TITLE
Daemon v0.4.1 cannot create servers

### ISSUE THREAD

**Issue by ET-Bent** [Pterodactyl/Panel#456]
The latest daemon version (`0.4.1`) is broken and incapable of creating new servers. 

Error upon creating a new server (of any type):

```
11:36:41.129Z FATAL wings: A fatal error occured during an operation.
    TypeError: callback is not a function
        at Async.auto.close_stream.callback (/srv/daemon/src/controllers/option.js:101:24)
        at runTask (/srv/daemon/node_modules/async/dist/async.js:1619:13)
        at /srv/daemon/node_modules/async/dist/async.js:1559:13
        at processQueue (/srv/daemon/node_modules/async/dist/async.js:1569:13)
        at taskComplete (/srv/daemon/node_modules/async/dist/async.js:1588:9)
        at /srv/daemon/node_modules/async/dist/async.js:1612:17
        at /srv/daemon/node_modules/async/dist/async.js:906:16
        at /srv/daemon/node_modules/graceful-fs/graceful-fs.js:99:16
        at /srv/daemon/node_modules/graceful-fs/graceful-fs.js:43:10
        at FSReqWrap.oncomplete (fs.js:123:15)
```

Reverting back to daemon version `0.4.0` solves the issue.

AIO command to revert and downgrade daemon:

```
service wings stop; mkdir -p /srv/daemon /srv/daemon-data; cd /srv/; tar czf daemon_041_backup.tar.gz daemon; rm -rf /srv/daemon/*; cd /srv/daemon; curl -Lo v0.4.0.tar.gz https://github.com/Pterodactyl/Daemon/archive/v0.4.0.tar.gz; tar --strip-components=1 -xzvf v0.4.0.tar.gz; npm install --only=production; cd /srv/; tar -xzvf /srv/daemon_041_backup.tar.gz daemon/config; cd /srv/daemon; npm start 
```

**Comment by DaneEveritt** [comment]
closed in https://github.com/Pterodactyl/Daemon/commit/69bbc397de7846bfaad864417ddeaac3ee65fe95
