### ISSUE TITLE
Plugins can't create any directory or file

### ISSUE THREAD

**Issue by notdeliable** [pterodactyl/panel#4624]
### Current Behavior

Almost every plugin can't create any directory or file.

### Expected Behavior

Plugins should be able to create directory or files.

### Steps to Reproduce

1. Delete files of plugins
2. Start the server

### Panel Version

1.11.2

### Wings Version

1.11.0

### Games and/or Eggs Affected

Purpur, Minecraft, 1.19.2

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#26 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#29 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#30 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#31 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\\Queue\\Jobs\\Job->fire()
#32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#33 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#34 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\\Queue\\Worker->daemon()
#35 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#36 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#37 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#38 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#39 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#40 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#41 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\\Container\\Container->call()
#42 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#43 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\\Component\\Console\\Command\\Command->run()
#44 /var/www/pterodactyl/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run()
#45 /var/www/pterodactyl/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#46 /var/www/pterodactyl/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#47 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#48 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#49 /var/www/pterodactyl/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#50 {main}, 2022-12-17 23:44:07)) at /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\\Database\\Connection->run()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\\Database\\Connection->statement()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3218): Illuminate\\Database\\Connection->insert()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php(64): Illuminate\\Database\\Query\\Builder->insert()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(251): Illuminate\\Queue\\Failed\\DatabaseUuidFailedJobProvider->log()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(198): Illuminate\\Queue\\Console\\WorkCommand->logFailedJob()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Illuminate\\Queue\\Console\\WorkCommand->Illuminate\\Queue\\Console\\{closure}()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(195): Illuminate\\Events\\Dispatcher->dispatch()
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(582): Illuminate\\Queue\\Jobs\\Job->fail()
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(528): Illuminate\\Queue\\Worker->failJob()
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(452): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts()
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(429): Illuminate\\Queue\\Worker->handleJobException()
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\\Queue\\Worker->daemon()
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#19 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\\Container\\Container->call()
#24 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/pterodactyl/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run()
#27 /var/www/pterodactyl/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/pterodactyl/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#30 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#31 /var/www/pterodactyl/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}

[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'field list' at /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:539)
[stacktrace]
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(539): PDO->prepare()
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\\Database\\Connection->run()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\\Database\\Connection->statement()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3218): Illuminate\\Database\\Connection->insert()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php(64): Illuminate\\Database\\Query\\Builder->insert()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(251): Illuminate\\Queue\\Failed\\DatabaseUuidFailedJobProvider->log()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(198): Illuminate\\Queue\\Console\\WorkCommand->logFailedJob()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Illuminate\\Queue\\Console\\WorkCommand->Illuminate\\Queue\\Console\\{closure}()
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(195): Illuminate\\Events\\Dispatcher->dispatch()
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(582): Illuminate\\Queue\\Jobs\\Job->fail()
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(528): Illuminate\\Queue\\Worker->failJob()
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(452): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts()
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(429): Illuminate\\Queue\\Worker->handleJobException()
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\\Queue\\Worker->daemon()
#19 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\\Container\\Container->call()
#26 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\\Component\\Console\\Command\\Command->run()
#28 /var/www/pterodactyl/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run()
#29 /var/www/pterodactyl/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#30 /var/www/pterodactyl/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#31 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#33 /var/www/pterodactyl/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
"}
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Please edit your message and set the error logs to the link from the panel logs command (as instructed by the issue template).

**Comment by matthewpi** [comment]
If this was an actual bug we would definitely have more then one report about it.  No update/reply recently, so this issue is being closed.
