### ISSUE TITLE
(err.code=EPROTO)

### ISSUE THREAD

**Issue by xyronexus** [Pterodactyl/Panel#489]
```
16:28:51.072Z FATAL wings: A fatal error caused the daemon to abort the startup. (err.code=EPROTO)
    Error: write EPROTO 140215037282112:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

        at exports._errnoException (util.js:1018:11)
        at WriteWrap.afterWrite (net.js:800:14)
    --
    additional: {
      "code": "EPROTO",
      "errno": "EPROTO",
      "syscall": "write"
    }
16:28:51.073Z ERROR wings: You should forcibly quit this process and attempt to fix the issue.
```
https://image.prntscr.com/image/9UhMqbLBQN2tq89A6qit3A.png
[error](https://image.prntscr.com/image/9UhMqbLBQN2tq89A6qit3A.png)

**Comment by schrej** [comment]
This looks like there is something wrong with your configuration. Check the Urls and see if all of them are correct regarding HTTPS.

**Comment by xyronexus** [comment]
One of them was from beginning. But now i switch to HTTP. Solved
