### ISSUE TITLE
Minecraft server does not start with mods magma, 1.18.2

### ISSUE THREAD

**Issue by 7elmen** [pterodactyl/panel#4919]
### Current Behavior

Minecraft server does not start with mods 

### Expected Behavior

Minecraft server does not start with mods

### Steps to Reproduce

none

### Panel Version

idk

### Wings Version

1.18.2

### Games and/or Eggs Affected

Minecraft, Magma

### Docker Image

.

### Error Logs

```bash
root@111115676~# java -Xms128M -Xmx5120M -Dfml.queryResult=confirm -Dlog4j2.formatMsgNoLookups=true -Dterminal.jline=false -Dterminal.ansi=true -DIReallyKnowWhatIAmDoingISwear=true -Djdk.module.illegalAccess=deny -Duser.timezone=Europe/Moscow -jar -XX:+UseNUMA -XX:G1ReservePercent=10 -XX:G1HeapWastePercent=10 -XX:+OptimizeStringConcat -XX:+TieredCompilation -XX:+EliminateLocks -XX:+UseSuperWord -XX:+OptimizeFill -XX:LoopUnrollMin=4 -XX:LoopMaxUnroll=16 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -Dfile.encoding=UTF-8 -XX:+DisableExplicitGC -XX:+UseFastJNIAccessors -XX:+UseParallelGC -jar Magma-1.18.2-40.2.10-5fc5c9e8-server.jar nogui

Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/magmafoundation/magma/utils/ServerInitHelper, offset=6

at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)

at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:479)

at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:440)

at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)

at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1133)

at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:920)

at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:828)

at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:786)

at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081)

at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431)

at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)

at java.instrument/sun.instrument.InstrumentationImpl.loadAgent0(Native Method)

at java.instrument/sun.instrument.InstrumentationImpl.loadAgent(InstrumentationImpl.java:578)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:564)

at java.base/sun.launcher.LauncherHelper.lambda$getMainClassFromJar$0(LauncherHelper.java:545)

at sun.launcher.LauncherHelper$$Lambda$2/0000000090362740.accept(Unknown Source)

at java.base/java.util.Optional.ifPresent(Optional.java:176)

at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:540)

at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:747)

at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)

error loading java agent in Magma-1.18.2-40.2.10-5fc5c9e8-server.jar

[Donator-6 Daemon]: ---------- Detected server process in a crashed state! ----------

[Donator-6 Daemon]: Exit code: 1

[Donator-6 Daemon]: Out of memory: false

[Donator-6 Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jcodeerd** [comment]
Sounds like you're using a host. I'd suggest to ask them, but I think your java version might be wrong.

**Comment by danny6167** [comment]
There is no such wings version as "v1.18.2"
And why does your log output start with "root@111115676~#". Pterodactyl containers do not run as root, so something has been changed there.

**Comment by Xteri08** [comment]
You are running on root using cli not pterodactyl
