### ISSUE TITLE
Not able to build development version

### ISSUE THREAD

**Issue by Danieljunek17** [pterodactyl/panel#5018]
### Current Behavior

vite v4.1.4 building for production...
✓ 2135 modules transformed.
"default" is not exported by "react/jsx-runtime", imported by "node_modules/.pnpm/@preact+signals-react@1.2.2_react@18.2.0/node_modules/@preact/signals-react/dist/signals.module.js".
file: /var/www/pterodactyl/node_modules/.pnpm/@preact+signals-react@1.2.2_react@18.2.0/node_modules/@preact/signals-react/dist/signals.module.js:1:84
1: import n,{Component as r,useMemo as t,useRef as e,useEffect as o}from"react";import u from"react/jsx-runtime";import ...
                                                                                       ^
error during build:
RollupError: "default" is not exported by "react/jsx-runtime", imported by "node_modules/.pnpm/@preact+signals-react@1.2.2_react@18.2.0/node_modules/@preact/signals-react/dist/signals.module.js".
    at error (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at Identifier.bind (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at VariableDeclarator.bind (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at VariableDeclaration.bind (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Program.bind (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Module.bindReferences (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13741:18)
    at Graph.sortModules (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25853:20)
    at Graph.build (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25737:14)
    at async file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26706:13
    at async catchUnfinishedHookActions (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at async rollupInternal (file:///var/www/pterodactyl/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26701:5)
    at async build (file:///var/www/pterodactyl/node_modules/.pnpm/vite@4.1.4_@types+node@18.14.1/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44664:18)
    at async CAC.<anonymous> (file:///var/www/pterodactyl/node_modules/.pnpm/vite@4.1.4_@types+node@18.14.1/node_modules/vite/dist/node/cli.js:813:9)
 ELIFECYCLE  Command failed with exit code 1.

### Expected Behavior

vite build to run properly

### Steps to Reproduce

run "pnpm build"

### Panel Version

development

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
v2 aka develop is not given support for, it is not ready for prod.

Use develop-v1.

**Comment by matthewpi** [comment]
This is known, `develop` is for a future upcoming version.  You should only be using the `1.0-develop` branch for now.
