### ISSUE TITLE
Mismatch in Daemon/Panel core.json token, panel responds with 404 instead of 403

### ISSUE THREAD

**Issue by 404uam** [Pterodactyl/Panel#506]
When the token in the panel node is mismatched with the one in the core.json, the panel will respond with a 404 error instead of a 403 error. As shown in Line 18 of the output.

```02:09:09.315Z  INFO wings: + ------------------------------------ +
02:09:09.327Z  INFO wings: | Running Pterodactyl Daemon v0.4.2    |
02:09:09.327Z  INFO wings: |        https://pterodactyl.io        |
02:09:09.330Z  INFO wings: |  Copyright 2015 - 2017 Dane Everitt  |
02:09:09.330Z  INFO wings: + ------------------------------------ +
02:09:09.330Z  INFO wings: Loading modules, this could take a few seconds.
02:09:10.694Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
02:09:10.721Z  INFO wings: Checking container networking environment...
02:09:10.746Z  INFO wings: Attempting to start SFTP service container...
02:09:10.790Z  INFO wings: Contacting panel to retrieve a list of currrent services available to the node.
02:09:10.873Z  INFO wings: Found network interface for daemon: pterodactyl_nw
02:09:10.902Z  INFO wings: SFTP container successfully booted.
02:09:10.909Z  INFO wings: Checking pterodactyl0 interface and setting configuration values.
02:09:10.911Z  INFO wings: Checking gateway for pterodactyl0
02:09:10.942Z  INFO wings: Gateway detected as 172.18.0.1 for pterodactyl0.
02:09:10.947Z  INFO wings: Configuring timezone file location...
02:09:12.178Z  INFO wings: Pterodactyl Daemon is up-to-date!
02:09:16.760Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})
    Error: Error while attempting to fetch list of services (HTTP/404)
        at Request.ex [as _callback] (/srv/daemon/src/controllers/service.js:93:29)
        at Request.self.callback (/srv/daemon/node_modules/request/request.js:188:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1171:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1091:12)
        at IncomingMessage.g (events.js:292:16)
        at emitNone (events.js:91:20)
02:09:16.763Z ERROR wings: You should forcibly quit this process and attempt to fix the issue.```

---------------------

**Comment by DaneEveritt** [comment]
closed in https://github.com/Pterodactyl/Panel/commit/9515128b8ad416fac3b7af254fdcd16b912caf9c
