### ISSUE TITLE
Daemon error

### ISSUE THREAD

**Issue by Killklli** [Pterodactyl/Panel#514]
Every time I open the file browser tab on a server the daemon kicks me this error

`bunyan: ERROR: Exception thrown from the "res" Bunyan serializer. This should never happen. This is a bug in that serializer function.
RangeError: Maximum call stack size exceeded
    at ServerResponse.getHeaders (/srv/daemon/node_modules/restify/lib/response.js:176:52)
    at ServerResponse.get (_http_outgoing.js:130:17)
    at ServerResponse.getHeaders (/srv/daemon/node_modules/restify/lib/response.js:177:17)
    at ServerResponse.get (_http_outgoing.js:130:17)
    at ServerResponse.getHeaders (/srv/daemon/node_modules/restify/lib/response.js:177:17)
    at ServerResponse.get (_http_outgoing.js:130:17)
    at ServerResponse.getHeaders (/srv/daemon/node_modules/restify/lib/response.js:177:17)
    at ServerResponse.get (_http_outgoing.js:130:17)
    at ServerResponse.getHeaders (/srv/daemon/node_modules/restify/lib/response.js:177:17)
    at ServerResponse.get (_http_outgoing.js:130:17)`

`root@Pterodactyl:/srv/daemon# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-81-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 68.83 GiB
Name: Pterodactyl
ID: PJ3K:UD7G:2ABU:N3DJ:VBBX:BGUR:GOWZ:5DXJ:C7ST:53TO:VU7X:PMLH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

**Comment by DaneEveritt** [comment]
Need to update all of our dependencies to support Nodejs v8.

**Comment by DaneEveritt** [comment]
Fixed in https://github.com/Pterodactyl/Daemon/commit/60446bcd954a93487d4cfd4a75fe00658f721589
