### ISSUE TITLE
Deleting suspended server throws 500 error in daemon

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#524]
Deleting suspended server throws error but still deletes the server. Most likely due to the dependency updates.

```
Server error: `DELETE https://chi.demo.ptdl.co:8443/servers` resulted in a `500 Internal Server Error` response: { "error": "(HTTP code 500) container not running - {\"message\":\"EOF\"}\n " }
```

```
03:21:31.982Z DEBUG wings: Clearing servers object... (server=ed066fdb-cca9-45c6-a011-06329b4b61f4)
03:21:31.989Z DEBUG wings: Attempting to remove container... (server=ed066fdb-cca9-45c6-a011-06329b4b61f4)
03:21:31.997Z DEBUG wings: Attempting to remove configuration files... (server=ed066fdb-cca9-45c6-a011-06329b4b61f4)
03:21:32.001Z DEBUG wings: Attempting to remove SFTP user... (server=ed066fdb-cca9-45c6-a011-06329b4b61f4)
03:21:32.052Z FATAL wings:
    (HTTP code 500) container not running - {"message":"EOF"}
     
    --
    Error: (HTTP code 500) container not running - {"message":"EOF"}
     
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:243:17
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:9)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
03:21:32.071Z DEBUG wings: Removed container. (server=ed066fdb-cca9-45c6-a011-06329b4b61f4)
03:21:32.072Z DEBUG wings: Removed configuration folder. null (server=ed066fdb-cca9-45c6-a011-06329b4b61f4)
03:26:34.067Z DEBUG wings: Clearing servers object... (server=649b9aed-f0ec-43df-9505-9501d5060861)
03:26:34.070Z DEBUG wings: Attempting to remove container... (server=649b9aed-f0ec-43df-9505-9501d5060861)
03:26:34.075Z DEBUG wings: Attempting to remove configuration files... (server=649b9aed-f0ec-43df-9505-9501d5060861)
03:26:34.076Z DEBUG wings: Attempting to remove SFTP user... (server=649b9aed-f0ec-43df-9505-9501d5060861)
03:26:34.101Z FATAL wings:
    (HTTP code 500) container not running - {"message":"EOF"}
     
    --
    Error: (HTTP code 500) container not running - {"message":"EOF"}
     
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:243:17
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:9)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
03:26:34.122Z DEBUG wings: Removed configuration folder. null (server=649b9aed-f0ec-43df-9505-9501d5060861)
03:26:34.125Z DEBUG wings: Removed container. (server=649b9aed-f0ec-43df-9505-9501d5060861)
```

**Comment by Sir3lit** [comment]
The issue has resurfaced in the Go wings

**Background (please complete the following information):**
* Panel or Daemon: Both?
* Version of Panel/Daemon: Dev build as of 4/9/2020
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win 10 Pro /  Chrome Beta

**Describe the bug**
Deleting a newly created server that is installing results in the daemon returning a 500 due to the container not existing
```
encountered error while handling HTTP request   {"server": "f58e6e02-ea43-4240-b205-8919db93bde6", "error_id": "bfb0810e-82e6-43bd-9c2b-02d4109592bc", "error": "Error: No such container: f58e6e02-ea43-4240-b205-8919db93bde6"}
```

You are then stuck with a `ghost` server in the panel, clicking delete sends the DELETE to the daemon but leaves a residual config file.

**To Reproduce**
1. Create Server
2. "Safely Delete" before install completes 
3. Error 500 is presented as a response from wings.

**Comment by DaneEveritt** [comment]
I haven't been able to reproduce this, and I believe it is also guarded against even more in https://github.com/pterodactyl/wings/commit/1f6789cba3cb888fe61fd5cb6e3f4adc1e189459

Please open a new issue if it persists as it would be affecting a completely different bit of software.
