### ISSUE TITLE
Panel cannot connect to my node correctly

### ISSUE THREAD

**Issue by T-Grave** [Pterodactyl/Panel#579]
## Environment
- Panel (v0.6.4) running inside a Docker container at `10.1.15.50`
- NGINX proxy with SSL enabled for `https://panel.mydomain.com` at `10.1.15.5`
- A single node (v0.4.3) running at `10.1.15.20`

**Node panel settings**
![image](https://user-images.githubusercontent.com/7956579/29070112-1563058e-7c3e-11e7-82fb-7c394a7c64b7.png)

**Node core.json config**:
```
{
  "web": {
    "host": "0.0.0.0",
    "listen": 8080,
    "ssl": {
      "enabled": false,
      "certificate": "/etc/letsencrypt/live/10.1.15.20/fullchain.pem",
      "key": "/etc/letsencrypt/live/10.1.15.20/privkey.pem"
    }
  },
  "docker": {
    "socket": "/var/run/docker.sock",
    "autoupdate_images": true,
    "interface": "172.18.0.1",
    "timezone_path": "/etc/timezone"
  },
  "sftp": {
    "path": "/srv/daemon-data",
    "port": 2022,
    "container": "adecf35e83ccd810f571f32fffe8ea7000eca1abea31bb234199f7623eb21073"
  },
  "logger": {
    "path": "logs/",
    "src": false,
    "level": "info",
    "period": "1d",
    "count": 3
  },
  "remote": {
    "base": "https://panel.mydomain.com"
  },
  "uploads": {
    "size_limit": 100
  },
  "keys": [
    "SOME_KEY"
  ]
}
```

## Problem
1. When I open my node's about page, the version polling keeps running for ever.
![image](https://user-images.githubusercontent.com/7956579/29070084-e8d0e3b0-7c3d-11e7-9f12-8e38bf408c44.png)

2. When I go to the servers tab I get the following error:
```
There was an error attempting to establish a WebSocket connection to the Daemon. This panel will not work as expected.

Error: xhr poll error
```

3. When I create a server, the node does actually create it, pulls all images and tries to boot it, but as you can see in my node it's logs it failed on the initital boot / setup (looks like some DNS issue) and I triggered a "reinstall" afterwards from the panel, it seemed to have reinstalled without issue, but now I cannot try and boot the server because of the same WebSocket error described in issue number 2.

```
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":30,"msg":"Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.","time":"2017-08-08T11:15:29.169Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":30,"msg":"Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.","time":"2017-08-08T11:15:51.980Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Completed rebuild process for server container.","time":"2017-08-08T11:15:53.536Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":40,"msg":"Server booting is now BLOCKED.","time":"2017-08-08T11:15:53.537Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Blocking server boot until option installation process is completed.","time":"2017-08-08T11:15:53.537Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Writing output of installation process to file. { file: '/srv/daemon/config/servers/419b54dd-7fe7-4db0-93c7-de7ac407e346/install.log' }","time":"2017-08-08T11:15:53.638Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":30,"msg":"Pulling image alpine:3.4 ... this could take a few minutes.","time":"2017-08-08T11:16:00.911Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Temporarily suspending server to avoid mishaps...","time":"2017-08-08T11:16:00.912Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":40,"msg":"Server has been suspended.","time":"2017-08-08T11:16:01.162Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Completed installation process for server.","time":"2017-08-08T11:16:20.847Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Server booting is now UNBLOCKED.","time":"2017-08-08T11:16:20.858Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":30,"msg":"Notified remote panel of server install status.","time":"2017-08-08T11:16:20.969Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Server status has been changed to STARTING","time":"2017-08-08T11:16:20.969Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Server status has been changed to OFF","time":"2017-08-08T11:16:20.970Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Server has been unsuspended.","time":"2017-08-08T11:16:21.087Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":30,"msg":"Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.","time":"2017-08-08T11:16:21.146Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":50,"err":{"message":"(HTTP code 500) server error - {\"message\":\"Get https://quay.io/v2/pterodactyl/core/manifests/java: dial tcp: lookup quay.io on 8.8.4.4:53: read udp 10.1.15.20:47854->8.8.4.4:53: i/o timeout\"}\n ","name":"Error","stack":"Error: (HTTP code 500) server error - {\"message\":\"Get https://quay.io/v2/pterodactyl/core/manifests/java: dial tcp: lookup quay.io on 8.8.4.4:53: read udp 10.1.15.20:47854->8.8.4.4:53: i/o timeout\"}\n \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:243:17\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:9)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"(HTTP code 500) server error - {\"message\":\"Get https://quay.io/v2/pterodactyl/core/manifests/java: dial tcp: lookup quay.io on 8.8.4.4:53: read udp 10.1.15.20:47854->8.8.4.4:53: i/o timeout\"}\n ","time":"2017-08-08T11:16:48.117Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":40,"msg":"Server booting is now BLOCKED.","time":"2017-08-08T11:20:04.079Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Blocking server boot until option installation process is completed.","time":"2017-08-08T11:20:04.080Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Writing output of installation process to file. { file: '/srv/daemon/config/servers/419b54dd-7fe7-4db0-93c7-de7ac407e346/install.log' }","time":"2017-08-08T11:20:04.206Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":30,"msg":"Pulling image alpine:3.4 ... this could take a few minutes.","time":"2017-08-08T11:20:16.791Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Temporarily suspending server to avoid mishaps...","time":"2017-08-08T11:20:16.791Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":40,"msg":"Server has been suspended.","time":"2017-08-08T11:20:17.131Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Completed installation process for server.","time":"2017-08-08T11:20:36.242Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Server booting is now UNBLOCKED.","time":"2017-08-08T11:20:36.253Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"level":30,"msg":"Notified remote panel of server install status.","time":"2017-08-08T11:20:36.366Z","v":0}
{"name":"wings","hostname":"game-agent-1","pid":9944,"server":"419b54dd-7fe7-4db0-93c7-de7ac407e346","level":30,"msg":"Server has been unsuspended.","time":"2017-08-08T11:20:36.530Z","v":0}
```

Thanks in advance for your help and awesome work on the panel so far!

**Comment by parkervcp** [comment]
When you have a panel that is https your daemons also need to run in https.

**Comment by DaneEveritt** [comment]
You also cannot use a private IP address unless this is **all** located within your local network.

**Comment by T-Grave** [comment]
@parkervcp ah, I see, I will setup https for my daemon and report back.

@DaneEveritt all machines are located on my local subnet


Thanks for the quick response guys!

**Comment by DaneEveritt** [comment]
This isn't really a bug with our software, rather a networking issue, closing this issue here, but you're more than welcome to continue this discussion on our Discord or forums. 👍
