### ISSUE TITLE
Bug in Wings 0.4.4 preventing any server installations

### ISSUE THREAD

**Issue by ET-Bent** [Pterodactyl/Panel#593]
Docker version `17.06.0-ce, build 02c1d87`
Daemon version `v0.4.4`
System `Ubuntu 16.04.3 LTS (64 bit)`

This issue occurs when creating a new server. Happened on several occasions in the past few days in support.

Downgrading the daemon to `v0.4.3` works as a current workaround. (Without changing any other system parameters)

```
09:39:23.686Z  WARN wings: Container was not found. Attempting to recreate it. (server=UUID)
09:39:23.689Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.
09:39:25.103Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
09:39:35.104Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
09:39:37.179Z FATAL wings:
    A fatal error was encountered while attempting to create a server. { Error: (HTTP code 500) server error - invalid bind mount spec "undefined:undefined:ro": invalid
 volume specification: 'undefined:undefined:ro': invalid mount config for type "volume": invalid mount path: 'undefined' mount path must be absolute 
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:243:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:273:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:242:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:218:14)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
      reason: 'server error',
      statusCode: 500,
      json: { message: 'invalid bind mount spec "undefined:undefined:ro": invalid volume specification: \'undefined:undefined:ro\': invalid mount config for type "volum
e": invalid mount path: \'undefined\' mount path must be absolute' } }
09:39:37.186Z  WARN wings: No container ID was defined in the server JSON, skipping container deletion step. (server=UUID)
09:39:37.351Z  INFO wings: Notified remote panel of server install status.
09:39:37.790Z  INFO wings: Server deleted. (server=UUID)
```

**Comment by DaneEveritt** [comment]
The heck. Will investigate tonight if no one submits a PR before then.
