### ISSUE TITLE
Wings Crash on start

### ISSUE THREAD

**Issue by jonitiso** [Pterodactyl/Panel#653]
when execute: sudo npm start

00:42:00.666Z  INFO wings: + ------------------------------------ +
00:42:00.671Z  INFO wings: | Running Pterodactyl Daemon v0.4.5    |
00:42:00.672Z  INFO wings: |        https://pterodactyl.io        |
00:42:00.672Z  INFO wings: |  Copyright 2015 - 2017 Dane Everitt  |
00:42:00.672Z  INFO wings: + ------------------------------------ +
00:42:00.672Z  INFO wings: Loading modules, this could take a few seconds.
00:42:00.981Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
00:42:01.028Z  INFO wings: Contacting panel to retrieve a list of currrent services available to the node.
00:42:01.031Z  INFO wings: Checking container networking environment...
00:42:01.045Z  INFO wings: Found network interface for daemon: pterodactyl_nw
00:42:01.046Z  INFO wings: Configuring timezone file location...
00:42:01.047Z  INFO wings: Checking pterodactyl0 interface and setting configuration values.
00:42:01.048Z  INFO wings: Checking gateway for pterodactyl0
00:42:01.060Z  INFO wings: Gateway detected as 172.18.0.1 for pterodactyl0.
00:42:01.068Z  INFO wings: Attempting to start SFTP service container...
00:42:01.076Z  INFO wings: SFTP container successfully booted.
00:42:01.311Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})
    SyntaxError: Unexpected token < in JSON at position 0
        at Object.parse (native)
        at Request.ex [as _callback] (/srv/daemon/src/controllers/service.js:101:40)
        at Request.self.callback (/srv/daemon/node_modules/request/request.js:188:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1171:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1091:12)
        at IncomingMessage.g (events.js:292:16)
00:42:01.314Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
ubuntu@ip-10-0-0-233:/srv/daemon$

**Comment by tenten8401** [comment]
Your /srv/daemon/config/core.json is malformed. Check it and try copy/pasting it again.

**Comment by jonitiso** [comment]
now i have this problem 

01:12:37.428Z  INFO wings: Server status has been changed to STARTING (server=bf87ba2d-bf36-4440-9699-8d167cf2635d)
01:12:37.527Z  INFO wings: Server status has been changed to OFF (server=bf87ba2d-bf36-4440-9699-8d167cf2635d)
01:12:37.528Z ERROR wings: (HTTP code 500) server error - driver failed programming external connectivity on endpoint maincr_bf87ba2d (6e2bb1b25f4d5ef71c76e7ca22d83724208e37481e21459f9b7c81c23575b342): Error starting userland proxy: listen tcp 54.200.6.244:25565: bind: cannot assign requested address  (server=bf87ba2d-bf36-4440-9699-8d167cf2635d)
    Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint maincr_bf87ba2d (6e2bb1b25f4d5ef71c76e7ca22d83724208e37481e21459f9b7c81c23575b342): Error starting userland proxy: listen tcp 54.200.6.244:25565: bind: cannot assign requested address
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:251:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:281:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:250:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:226:14)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by DaneEveritt** [comment]
This is not a bug with this software, it is a configuration issue on your end. Please use our [Discord](https://pterodactyl.io/discord) or [Forums](https://forums.pterodactyl.io) for further assistance.
