### ISSUE TITLE
Wings (Daemon) Auto-Deploy failed to fetch configuration from panel

### ISSUE THREAD

**Issue by Porama6400** [Pterodactyl/Panel#828]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.4
* Server's OS: Ubuntu Server 16.04 LTS
* Your Computer's OS & Browser: Windows 10, Chrome

I have an error while I use **Auto-Deploy** to fetch configuration from Pterodactyl Panel

* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.4
* Server's OS: Ubuntu Server 16.04 LTS
* Your Computer's OS & Browser: Windows 10, Chrome

I have an error while I use **Auto-Deploy** to fetch configuration from Pterodactyl Panel

    Fetching configuration from panel
    undefined:1
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    ^
    
    SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/srv/daemon/scripts/configure.js:158:35)
    at Request.self.callback(/srv/daemon/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)

**Comment by DaneEveritt** [comment]
Do you already have a config file?

**Comment by Porama6400** [comment]
I already have config file but It ask if I want to replace the old one, so I tell it to replace the old one

The old one I typed it manually then It wouldn't start so I guess I type something wrong

**Comment by DaneEveritt** [comment]
Your panel is setup incorrectly, it’s grabbing a 404 page it looks like.

**Comment by Porama6400** [comment]
So what page is it trying to access so I can check if it is true that it display incorrectly

**Comment by schrej** [comment]
`<panelurl>/daemon/configure/<token>`
