### ISSUE TITLE
Daemon does not start because of not existing docker image

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#886]
My Daemon fails to start due to an old docker image in a egg that does not exist. 
Please let the daemon ignore and skip instead of death.

I cant change or rebuild the container if the daemon does not start. so until i delete the server, i am unable to change the image. (i could edit the configuration file..)

```
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"+ ------------------------------------ +","time":"2018-01-20T20:41:25.092Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"| Running Pterodactyl Daemon v0.0.0-canary    |","time":"2018-01-20T20:41:25.094Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"|        https://pterodactyl.io        |","time":"2018-01-20T20:41:25.094Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"|  Copyright 2015 - 2017 Dane Everitt  |","time":"2018-01-20T20:41:25.094Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"+ ------------------------------------ +","time":"2018-01-20T20:41:25.094Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Loading modules, this could take a few seconds.","time":"2018-01-20T20:41:25.094Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Modules loaded, starting Pterodactyl Daemon...","time":"2018-01-20T20:41:27.501Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Configuring user pterodactyl (id: 118) as the owner of all server files.","time":"2018-01-20T20:41:28.290Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Contacting panel to retrieve a list of currrent Eggs available to the node.","time":"2018-01-20T20:41:28.294Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Checking container networking environment...","time":"2018-01-20T20:41:28.358Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Found network interface for daemon: pterodactyl_nw","time":"2018-01-20T20:41:28.373Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Configuring timezone file location...","time":"2018-01-20T20:41:28.374Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Checking pterodactyl0 interface and setting configuration values.","time":"2018-01-20T20:41:28.374Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Checking gateway for pterodactyl0","time":"2018-01-20T20:41:28.374Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Gateway detected as 172.18.0.1 for pterodactyl0.","time":"2018-01-20T20:41:28.408Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Checking current files aganist panel response.","time":"2018-01-20T20:41:28.754Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Attempting to load servers and initialize daemon...","time":"2018-01-20T20:41:28.855Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"e50f8899-e6b9-455f-a624-adcdb33c1ce4","level":30,"msg":"Server status has been changed to ON","time":"2018-01-20T20:41:28.946Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"2cb21377-797f-4f86-a704-b2d4793ba128","level":30,"msg":"Server status has been changed to ON","time":"2018-01-20T20:41:28.948Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"e50f8899-e6b9-455f-a624-adcdb33c1ce4","level":30,"msg":"Daemon detected that the server container is currently running, re-attaching to it now!","time":"2018-01-20T20:41:29.071Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"2cb21377-797f-4f86-a704-b2d4793ba128","level":30,"msg":"Daemon detected that the server container is currently running, re-attaching to it now!","time":"2018-01-20T20:41:29.075Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"183c9920-d050-4a7c-8fcf-6a8bb3095fae","level":40,"msg":"Container was not found. Attempting to recreate it.","time":"2018-01-20T20:41:29.079Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"f7bd6bee-7833-4740-bab5-ea5b71d2948a","level":40,"msg":"Container was not found. Attempting to recreate it.","time":"2018-01-20T20:41:29.080Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"e1097bf2-49e2-4daa-ace5-b8ba55ca5f8f","level":40,"msg":"Container was not found. Attempting to recreate it.","time":"2018-01-20T20:41:29.081Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Checking if we need to update image quay.io/pterodactyl/core:source, if so it will happen now.","time":"2018-01-20T20:41:29.082Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Checking if we need to update image quay.io/cply/docker:dev, if so it will happen now.","time":"2018-01-20T20:41:29.084Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Checking if we need to update image quay.io/epic-gaming/docker-containers:garrysmod, if so it will happen now.","time":"2018-01-20T20:41:29.086Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.","time":"2018-01-20T20:41:31.125Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":60,"err":{"message":"(HTTP code 500) server error - unauthorized: access to the requested resource is not authorized ","name":"Error","stack":"Error: (HTTP code 500) server error - unauthorized: access to the requested resource is not authorized \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:281:9)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"additional":{"reason":"server error","statusCode":500,"json":null},"msg":"A fatal error caused the daemon to abort the startup.","time":"2018-01-20T20:41:31.160Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":50,"msg":"You should forcibly quit this process (CTRL+C) and attempt to fix the issue.","time":"2018-01-20T20:41:31.161Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Pulling image quay.io/epic-gaming/docker-containers:garrysmod ... this could take a few minutes.","time":"2018-01-20T20:41:31.185Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.","time":"2018-01-20T20:41:41.125Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Pulling image quay.io/epic-gaming/docker-containers:garrysmod ... this could take a few minutes.","time":"2018-01-20T20:41:41.185Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"f7bd6bee-7833-4740-bab5-ea5b71d2948a","level":30,"msg":"Completed rebuild process for server container.","time":"2018-01-20T20:41:50.497Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"level":30,"msg":"Pulling image quay.io/epic-gaming/docker-containers:garrysmod ... this could take a few minutes.","time":"2018-01-20T20:41:51.186Z","v":0}
{"name":"wings","hostname":"srv01","pid":30728,"server":"e1097bf2-49e2-4daa-ace5-b8ba55ca5f8f","level":30,"msg":"Completed rebuild process for server container.","time":"2018-01-20T20:41:54.165Z","v":0}
```
---
* Daemon: LATEST develop
* Server's OS: ubuntu 16.04
* Your Computer's OS & Browser: win10 FFDE

**Comment by DaneEveritt** [comment]
I don't think the daemon should skip that as the server is completely unusable if the docker image no longer exists. To me that reads as a fatal error that cannot be recovered from without just dropping the server completely from the daemon leading to what I can already see as being confusing issues on the Panel.

/cc @Pterodactyl/developers for more thoughts here.

**Comment by ProJaCore** [comment]
@DaneEveritt yeah but if i have a Server with an old image and the daemon is not running, then i am unable to change it. instead implement a funciton that will notify the server as "not funcitonal"

**Comment by DaneEveritt** [comment]
Fair point, I'll make adjustments so it works like it does when the egg is missing from the machine.
