### ISSUE TITLE
[Beta] FMgr +FTP | Issues with symlinks

### ISSUE THREAD

**Issue by MarkL4YG** [Pterodactyl/Panel#890]
* Affected: Panel + SFTP 
* Version of Panel: ``origin/develop``
* Version of Daemon: ``0.5.0-beta.5``
* Server's OS: Ubuntu 16.04.3 LTS w/ LAMP (MariaDB)
* Your Computer's OS & Browser: Windows 10 & Chrome / FF

## Details:
We created a custom service for automatic installation of various Minecraft services we use.
This service symlinks its actual server jar file to ``{{SERVER_JARFILE}}``. This seems to cause issues with both the file manager and SFTP connections.

### SFTP
Reports an error when connecting: ``Error:	Reading directory .: no such file or directory``
I currently don't know where to search for server logs for this. But I'll attach them when I found them.

### File manager
The file manager returns ``HTTP/500`` when accessed (maybe because the symlink is located right in the home directory).

__Panel log__
Here's the untruncated panel log:
```
[2018-01-22 19:29:52] production.WARNING: GuzzleHttp\Exception\ServerException: Server error: `GET https://<domain>:5000/v1/server/directory/%2F` resulted in a `500 Internal Server Error` response:
{
    "error": "ENOENT: no such file or directory, stat '/fearnixx/prod/srv/daemon-data/08f97754-0e5d-4b02-bde5-bb9cbc94ce07/Waterfall.jar'"
}
 in /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /fearnixx/prod/pterodactyl/panel/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 /fearnixx/prod/pterodactyl/panel/app/Repositories/Daemon/FileRepository.php(85): GuzzleHttp\Client->request('GET', 'server/director...')
#11 /fearnixx/prod/pterodactyl/panel/app/Http/Controllers/Server/Files/RemoteRequestController.php(69): Pterodactyl\Repositories\Daemon\FileRepository->getDirectory('/')
#12 [internal function]: Pterodactyl\Http\Controllers\Server\Files\RemoteRequestController->directory(Object(Illuminate\Http\Request), 'leO8XzbF')
#13 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('directory', Array)
#15 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Pterodactyl\Http\Controllers\Server\Files\RemoteRequestController), 'directory')
#16 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#17 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#18 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /fearnixx/prod/pterodactyl/panel/app/Http/Middleware/Server/AuthenticateAsSubuser.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Pterodactyl\Http\Middleware\Server\AuthenticateAsSubuser->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /fearnixx/prod/pterodactyl/panel/app/Http/Middleware/Server/AccessingValidServer.php(101): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Pterodactyl\Http\Middleware\AccessingValidServer->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /fearnixx/prod/pterodactyl/panel/app/Http/Middleware/RequireTwoFactorAuthentication.php(89): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Pterodactyl\Http\Middleware\RequireTwoFactorAuthentication->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /fearnixx/prod/pterodactyl/panel/app/Http/Middleware/LanguageMiddleware.php(52): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Pterodactyl\Http\Middleware\LanguageMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#56 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#57 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#58 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#59 /fearnixx/prod/pterodactyl/panel/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /fearnixx/prod/pterodactyl/panel/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 /fearnixx/prod/pterodactyl/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#80 /fearnixx/prod/pterodactyl/panel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#81 {main}
```

### Daemon
__Logs__
Here is the only error appearing in the daemon log in case it's related:
```
{"name":"wings","hostname":"<domain>","pid":14316,"server":"08f97754-0e5d-4b02-bde5-bb9cbc94ce07","level":40,"err":{"message":"Unable to determine size of server data folder, exited with code 1 signal null.","name":"Error","stack":"Error: Unable to determine size of server data folder, exited with code 1 signal null.\n    at ChildProcess.Exec.on (/fearnixx/prod/srv/daemon/src/controllers/fs.js:89:29)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)"},"msg":"Unable to determine size of server data folder, exited with code 1 signal null.","time":"2018-01-22T18:19:48.016Z","v":0}
```

### Misc. information
This service/egg is based on a custom docker image located on [Gitlab](https://gitlab.com/fearnixxgaming/docker/minecraft-server).
Image URL: ``registry.gitlab.com/fearnixxgaming/docker/minecraft-server:latest``
There's currently no dedicated installation script installed in the egg. Everything is handled by the container and entrypoint.
Relevant setup information can be viewed in the entrypoint script.
We're currently testing with ``SERVER_BRANCH="WATERFALL"`` 

In its current state this image appears to work as the Waterfall instance successfully starts up but appears unconfigurable due to this issue.

---
If you happen to need any additional information feel free to ask for it.

Kind regards
\- Mark

**Comment by DaneEveritt** [comment]
Can you export your egg config for this and DM it to me on Discord or upload it here?

**Comment by MarkL4YG** [comment]
There you go: https://gist.github.com/MarkL4YG/f5ccfbc6c2941402636fd291b75368a2

**Comment by DaneEveritt** [comment]
This was fixed in #888 I believe. Please reopen if it is not fixed.

**Comment by MarkL4YG** [comment]
I will test this later in the day and tell you when I've got results.

**Comment by MarkL4YG** [comment]
I suppose I'd need to run the latest daemon in order to test the fix?

**Comment by DaneEveritt** [comment]
Yes @MarkL4YG

**Comment by MarkL4YG** [comment]
In that case I'll have to wait for the ``bind`` thingy.

**Comment by MarkL4YG** [comment]
Daemon RC.1 finally upgraded without the strange "bind" stuff 👌 
Issue seems to be resolved. 👍 
I suppose the symbolic link is currently hidden on purpose? (Maybe a placeholder in the file manager may be better in the future)

**Comment by DaneEveritt** [comment]
The symlink is hidden if it is missing. I think something is wrong with your setup, I was able to view symlinks in the file manager. A good test for this is to comment out the code below and restart the daemon and see if it throws an ENOENT error.

https://github.com/Pterodactyl/Daemon/blob/42af5def57b733636589a1517b87cf46c2d44402/src/controllers/fs.js#L479-L481

**Comment by MarkL4YG** [comment]
well... the symlink is the jar file loaded and then run by Java and since the server starts without any issues I would assume the symlink is indeed valid.  
I'll have a look and report when I've got more info.

**Comment by MarkL4YG** [comment]
Hey @DaneEveritt . May I amend the issue or should I create a new one for the following?  
Broken/Invalid symlinks are not being displayed by the file manager which makes it impossible to delete them using Pterodactyl. Maybe displaying them anyways so one can delete them would be a more usable approach.

**Comment by DaneEveritt** [comment]
Thats not an issue, theres no way for Nodejs to handle those broken symlinks without throwing errors, so theres not really a way to make that work as far as I know.

**Comment by MarkL4YG** [comment]
hmm... Maybe I'll take a look myself then. It seems like this shouldn't be impossible. There's questions like [this one](https://stackoverflow.com/questions/23253332/check-if-a-symlink-exists-in-node-js) for example.   
Anyways you'll know when I come up with anything.
