### ISSUE TITLE
Found error log Laravel.log

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#896]
I found a unique log file named laravel.log inside the pterodactyl/storage/logs folder and wanted to share it here. maybe it will help progress: (i dont know how i could reproduce this..)
```
[2018-01-26 18:59:56] production.ERROR: Parse error: syntax error, unexpected '<<' (T_SL), expecting ']' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '<<' (T_SL), expecting ']' at /var/www/html/pterodactyl/config/app.php:12)
[stacktrace]
#0 /var/www/html/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#1 /var/www/html/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#2 /var/www/html/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#3 /var/www/html/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#4 /var/www/html/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#5 /var/www/html/pterodactyl/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#6 {main}
"}
```
---------------------
* Version of Panel: 655d2485
* Server's OS: ubuntu 16.04
* Your Computer's OS & Browser: FFDE WIN10

**Comment by parkervcp** [comment]
Unless you have what caused it it's not really helpful.

**Comment by DaneEveritt** [comment]
You have bad code in your config/app.php file on line 12.
