### ISSUE TITLE
A fatal error was encountered while attempting to create a server.

### ISSUE THREAD

**Issue by hexosse** [pterodactyl/Panel#966]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.4.5 
* Server's OS: Ubuntu 16.04

I finally manage to get the panel and the daemon to work both on the same host and each in a docker container.

The panel is in a docker container running php-fpm 7.1 and the daemon in a container running node 8. When I log into the panel all is working correctly and both are able to communicate. However, when I try to **create** a server I got the following error :

```Docker
09:51:57.457Z  INFO wings: + ------------------------------------ +
09:51:57.459Z  INFO wings: | Running Pterodactyl Daemon v0.4.5    |
09:51:57.459Z  INFO wings: |        https://pterodactyl.io        |
09:51:57.459Z  INFO wings: |  Copyright 2015 - 2017 Dane Everitt  |
09:51:57.459Z  INFO wings: + ------------------------------------ +
09:51:57.459Z  INFO wings: Loading modules, this could take a few seconds.
09:51:57.682Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
09:51:57.693Z DEBUG wings: Tar module found on server.
09:51:57.697Z DEBUG wings: Unzip module found on server.
09:51:57.739Z  INFO wings: Contacting panel to retrieve a list of currrent services available to the node.
09:51:57.739Z  INFO wings: Checking container networking environment...
09:51:57.747Z  INFO wings: Found network interface for daemon: pterodactyl_nw
09:51:57.747Z  INFO wings: Configuring timezone file location...
09:51:57.747Z  INFO wings: Checking pterodactyl0 interface and setting configuration values.
09:51:57.747Z  INFO wings: Checking gateway for pterodactyl0
09:51:57.755Z  INFO wings: Gateway detected as 172.30.0.1 for pterodactyl0.
09:51:57.758Z  INFO wings: Attempting to start SFTP service container...
09:51:57.771Z  INFO wings: SFTP container successfully booted.
09:51:57.783Z  INFO wings: Checking current files aganist panel response.
09:51:57.785Z  INFO wings: Attempting to load servers and initialize daemon...
09:51:57.787Z  INFO wings: Configuring websocket for daemon stats...
09:51:57.827Z  WARN wings: + ---------------------------- WARNING! ---------------------------- +
09:51:57.827Z  WARN wings: Pterodactyl Daemon is not up-to-date!
09:51:57.827Z  WARN wings:
09:51:57.827Z  WARN wings: Installed: v0.4.5
09:51:57.827Z  WARN wings:    Stable: v0.5.1
09:51:57.828Z  WARN wings:   Release: https://github.com/Pterodactyl/Daemon/releases/v0.5.1
09:51:57.828Z  WARN wings: + ------------------------------------------------------------------ +
09:51:57.830Z  INFO wings: Pterodactyl Daemon is now listening for insecure connections on 0.0.0.0:8080
09:52:57.096Z DEBUG wings: Updating passed JSON to route correct interfaces. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:57.096Z DEBUG wings: Creating SFTP user on the system... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:57.239Z DEBUG wings: Retrieving the user's ID... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:57.336Z DEBUG wings: User ID is: 15000 (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:57.339Z  WARN wings: Container was not found. Attempting to recreate it. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:57.340Z DEBUG wings: Removing old server container. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:57.342Z DEBUG wings: Rebuilding server container... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:57.343Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.
09:52:58.684Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
09:52:58.699Z DEBUG wings: Creating new container... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.750Z DEBUG wings: New container successfully created with ID 6873bc240393 (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.750Z DEBUG wings: Containers successfully rotated, updating stored configuration. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.756Z  INFO wings: Completed rebuild process for server container. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.839Z DEBUG wings: Loaded configuration and initalized server. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.839Z  WARN wings: Server booting is now BLOCKED. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.839Z  INFO wings: Blocking server boot until option installation process is completed. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.840Z DEBUG wings: Contacting remote server to pull scripts to be used. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.840Z DEBUG wings: Contacting panel to determine scripts to run for option processes. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.863Z DEBUG wings: Writing temporary file to be handed into the Docker container. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.865Z DEBUG wings: Pulling alpine:3.4 image if it is not already on the system. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:52:58.866Z  INFO wings: Writing output of installation process to file. { file: '/srv/daemon/config/servers/f252ec95-0554-4165-be4c-98fa40215d05/ins                                tall.log' } (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:00.149Z  INFO wings: Pulling image alpine:3.4 ... this could take a few minutes.
09:53:00.575Z  INFO wings: Temporarily suspending server to avoid mishaps... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:00.577Z DEBUG wings: Running privileged docker container to perform the installation process. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:00.582Z DEBUG wings: Server is has been marked as requiring a rebuild on next boot cycle. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:00.672Z  WARN wings: Server has been suspended. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.752Z  INFO wings: Completed installation process for server. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.753Z DEBUG wings: Properly chowning all server files and folders after installation. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.760Z FATAL wings:
    A fatal error was encountered while attempting to create a server. Error: Unable to set ownership of files properly, exited with code 1 signal null                                .
        at ChildProcess.Exec.on (/srv/daemon/src/controllers/fs.js:103:29)
        at ChildProcess.emit (events.js:160:13)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
09:53:03.765Z DEBUG wings: Clearing servers object... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.765Z DEBUG wings: Attempting to remove container... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.766Z  WARN wings: No container ID was defined in the server JSON, skipping container deletion step. (server=f252ec95-0554-4165-be4c-98fa40215d                                05)
09:53:03.766Z DEBUG wings: Attempting to remove configuration files... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.766Z DEBUG wings: Attempting to remove SFTP user... (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.776Z DEBUG wings: Removed configuration folder. null (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.801Z  WARN wings:
    An error occured while attempting to alert the panel of server install status. { code: 500,
      responseBody: '{"error":"An unhandled exception was encountered with this request.","http_code":true,"trace":null}' }
09:53:03.944Z DEBUG wings: Removed SFTP user. (server=f252ec95-0554-4165-be4c-98fa40215d05)
09:53:03.944Z  INFO wings: Server deleted. (server=f252ec95-0554-4165-be4c-98fa40215d05)
```

This error append at the end of the install process when ```this.server.fs.chown('/', callback);``` is executed in ```option.js```

I have no idea why this is not working, any help would be appreciated.

**Comment by ET-Bent** [comment]
Is it possible that your daemons data path is not existing?
What's the path you set in your `core.json``?

**Comment by hexosse** [comment]
Unfortunately, the daemon data path is set to ```/srv/daemon-data``` in ```core.json``` and the path exist in the container.

I thought it could be because of the symbolic link I had on this folder so I removed it but I still have the problem.

**Comment by DaneEveritt** [comment]
Since this is on an older version of the Daemon you'd need to update and see if it continues to happen there for this bug to be worked. It is a weird one since I've never seen it happen to others, but its also on a no-longer-current release.
