### ISSUE TITLE
SFTP Not Working

### ISSUE THREAD

**Issue by pchard** [pterodactyl/Panel#969]
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.1
* Server's OS: Ubuntu 17.10
* Your Computer's OS & Browser: Windows 10 - Chrome

## Add Details Below:

11:45:55.813Z  WARN wings: Panel reported an invalid set of SFTP credentials or a malformed request. (responseCode=404, requestUrl=https://panel.********.net/api/remote/sftp, username=a*****.a*****)
11:45:55.955Z FATAL wings: A fatal error occured during an operation.
    TypeError: Cannot read property 'server' of undefined
        at Client.client.on.on.on.err (/srv/daemon/src/http/sftp.js:487:30)
        at emitOne (events.js:96:13)
        at Client.emit (events.js:188:7)
        at SSH2Stream.<anonymous> (/srv/daemon/node_modules/ssh2/lib/server.js:311:10)
        at emitOne (events.js:101:20)
        at SSH2Stream.emit (events.js:188:7)
        at onDISCONNECT (/srv/daemon/node_modules/ssh2-streams/lib/ssh.js:2204:10)
        at SSH2Stream.<anonymous> (/srv/daemon/node_modules/ssh2-streams/lib/ssh.js:203:5)
        at emitMany (events.js:127:13)
        at SSH2Stream.emit (events.js:201:7)

--> wings request log = nothing / no entry

--> NGINX access log: 127.0.0.1 - - [21/Feb/2018:12:47:58 +0100] "POST /api/remote/sftp HTTP/1.1" 404 92 "-" "-"

**Comment by lancepioch** [comment]
Your daemon can't find your panel. 404 means that the url is missing.

Perhaps the ip has changed and the dns hasn't resolved yet or you misspelled the url when setting up the panel.

**Comment by pchard** [comment]
@lancepioch 
Someone from the support channel on discord told me to post this issue.

FlatronEZ is his name.

**Comment by lancepioch** [comment]
Either your SFTP username or password is incorrect.

You are hitting this exception: https://github.com/pterodactyl/Panel/blob/e7e50bc45d44f768eef03b9f83b9c58982b1de24/app/Http/Controllers/API/Remote/SftpController.php#L72-L76
